import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Badge,Select,Spinner} from '@fluentui/react-components';
import {Notice,PageHeading,PrintButton,num} from '../../components/common';
import Chart from '../../components/Chart';
type Row=Record<string,any>;
const pct=(v:number|null)=>v==null?'未验证':`${num(v*100,3)}%`;
const pp=(v:number|null)=>v==null?'未验证':`${num(v*100,3)}个百分点`;
const money=(v:number|null)=>v==null?'未验证':`¥${num(v,0)}`;
const modes:Record<string,string>={annual:'年度',semiannual:'半年',quarterly:'季度','absolute-5pp':'绝对偏离5个百分点','relative-20pct':'相对偏离20%','cashflow-only':'只用现金流'};
export default function CNYImplementability(){
 const [r,setR]=useState<Row|null>(null),[error,setError]=useState(false),[archive,setArchive]=useState<Row|null>(null),[scenario,setScenario]=useState('B'),[mode,setMode]=useState('annual');
 useEffect(()=>{fetch('./crisis-v32-cny/results.json').then(x=>{if(!x.ok)throw Error();return x.json();}).then(setR).catch(()=>setError(true));fetch('./crisis-v32-cny/review-archive.json').then(x=>x.ok?x.json():null).then(setArchive).catch(()=>{});},[]);
 const rows=useMemo(()=>r?.proxy_summary.filter((x:Row)=>x.scenario===scenario&&x.mode===mode)||[],[r,scenario,mode]);
 const curves=useMemo(()=>r?.proxy_curves.filter((x:Row)=>x.scenario===scenario)||[],[r,scenario]);
 const strong=r?.historical_frozen.find((x:Row)=>x.id==='global60-bond40'),v3=r?.historical_frozen.find((x:Row)=>x.id==='v3-balanced');
 if(!r)return <div className="page">{error?<Notice title="研究资料暂时未载入"><a href="./crisis-v32-cny/V3.2_IMPLEMENTABILITY_REPORT.md">打开报告</a></Notice>:<Spinner label="加载人民币税后可实施性研究"/>}</div>;
 const evidence=r.evidence_round2,diagnostic=evidence?.product_diagnostic;
 const annualStrong=r.proxy_summary.find((x:Row)=>x.id==='global60'&&x.scenario===scenario&&x.mode==='annual'),annualV3=r.proxy_summary.find((x:Row)=>x.id==='v3'&&x.scenario===scenario&&x.mode==='annual');
 return <div className="page model-page cny-study"><div className="page-breadcrumb"><Link to="/models">模型实验室</Link> / V3.2 实施现实</div>
 <PageHeading eyebrow="CNY AFTER-TAX IMPLEMENTABILITY STUDY · V3.2" title="人民币税后：全球配置值得实施吗？" summary="大陆个人 · 人民币收入与生活负债 · 普通境内证券及基金账户" action={<PrintButton/>}/>
 <div className="tag-row"><Badge color="danger" appearance="tint">FREEZE / IMPLEMENTATION BLOCKED</Badge><Badge color="warning" appearance="tint">IMPLEMENTATION NOT VALIDATED</Badge><Badge appearance="tint">30 / 30 / 30 / 10 冻结</Badge></div>
 <Notice title="当前回答：数据不足，不能发布真实税后排名">{r.implementation_answer} 产品映射、H11006/N11006、历史费率、QDII同步溢价和真实执行仍有缺口。下方数值压力不等于大陆投资者实际收益。</Notice>
 <section className="model-section"><h2>强基准继续在首屏</h2><div className="freeze-comparison">{[{row:strong,title:'全球股票60%＋中国国债40%',tag:'强基准 · 必须保留'},{row:v3,title:'V3冻结30%中国 / 30%全球 / 30%国债 / 10%黄金',tag:'冻结研究组合'}].map(({row,title,tag})=><article className="v2-summary-card" key={tag}><Badge appearance="tint">{tag}</Badge><h3>{title}</h3><dl><div><dt>原V3理论CAGR</dt><dd>{pct(row.cagr)}</dd></div><div><dt>原V3理论MDD</dt><dd>{pct(row.maxDrawdown)}</dd></div><div><dt>CNY税后CAGR</dt><dd>未验证</dd></div><div><dt>实盘资格</dt><dd>BLOCKED</dd></div></dl></article>)}</div><p>V3只有 {r.rolling.winsVsGlobal60} / {r.rolling.windows} 个滚动窗口领先。四档V3.1成本压力未稳定翻盘；保留这些结果，不将中国国债腿偷换成美国债券。</p><div className="module-links">{['investor','tax','fx','products','qdii','backtest','complexity','verdict'].map((id,i)=><a key={id} href={`#cny-${id}`} onClick={(event)=>{event.preventDefault();document.getElementById(`cny-${id}`)?.scrollIntoView({behavior:"smooth"});}}>{String(i+1).padStart(2,'0')} {['投资者','税与监管','汇率','产品映射','QDII','税后研究','复杂性','结论'][i]}</a>)}</div></section>
 <section className="model-section" id="cny-investor"><h2>01 Investor Reality · 投资者现实</h2><div className="guard-grid"><div><span className="meta">本金 / 收入 / 生活负债</span><p>¥100,000 / CNY / CNY</p></div><div><span className="meta">默认账户</span><p>普通境内证券账户、基金账户</p></div><div><span className="meta">境外账户、离岸资金、机构额度</span><p>不作默认假设</p></div></div><div className="table-scroll"><table><thead><tr><th>Research Portfolio</th><th>Implementable Portfolio</th></tr></thead><tbody><tr><td>允许ACWI/GLD与指数代理，研究历史风险；基金代理已含费用，不能称纯毛资产收益。</td><td>指定日期真实可买产品；全部产品、税务、准入、费率、时点和数据门槛通过才能批准。</td></tr></tbody></table></div><p>五层准入分别核查：Legal、Account、Capital、Product、Liquidity。个人年度购汇额度不等于自由境外证券投资许可。一级暂停与二级交易独立；可交易还须价格、预算和证据合格。</p></section>
 <section className="model-section" id="cny-tax"><h2>02 Tax & Regulation · 税收和监管</h2><Notice title="税率按所得与有效期匹配">基金底层预扣、产品净值内税费、投资者税负分别处理。文件原文核实不等于某只QDII/黄金ETF适用已确认；未知类别抛出 TAX TREATMENT UNCERTAIN。境外税抵免须有实际缴税及适用凭证，不简单重复扣税。</Notice><div className="table-scroll" tabIndex={0}><table><thead><tr><th>所得类别 / 主体</th><th>适用与范围</th><th>发布日期 / 生效 / 失效</th><th>证据与状态</th></tr></thead><tbody>{r.tax_rules.map((x:Row)=><tr key={x.id}><th>{x.category}<p>大陆居民个人</p></th><td>{x.rate==null?'TAX TREATMENT UNCERTAIN':pct(x.rate)}<p>{x.scope}</p>{x.tiers&&<p>按持有公历月/年分档；非统一20%</p>}</td><td>{x.published||'未验证'}<p>{x.effective} → {x.expires||'文件未列固定失效日；仍须复核变更'}</p></td><td>{x.verified?'A · 原文已核实，产品适用另审':'未通过应用核验'}<p>{x.source_id}</p></td></tr>)}</tbody></table></div></section>
 <section className="model-section" id="cny-fx"><h2>03 FX Return ≠ FX Friction</h2><p>外币资产增长×汇率增长＝人民币财富增长。汇率变化是收益及风险；银行买卖点差、汇款和券商兑换才是交易摩擦。人民币QDII份额不要求个人逐笔换美元，基金内部换汇与底层预扣已进入NAV时不再外扣。</p><div className="table-scroll"><table><thead><tr><th>冻结代理端点</th><th>本币资产总收益</th><th>USD/CNY总变化</th><th>乘法交互</th><th>CNY总收益</th><th>实际换汇费</th></tr></thead><tbody>{r.fx.map((x:Row)=><tr key={x.asset}><th>{x.asset}</th><td>{pct(x.asset_return)}</td><td>{pct(x.fx_return)}</td><td>{pct(x.interaction)}</td><td>{pct(x.cny_return)}</td><td>未验证</td></tr>)}</tbody></table></div><p>上述是原V3代理起终点恒等式，不是组合经济汇率归因。ACWI底层多币种、黄金也不是纯美元敞口；税务换算中间价与投资估值和兑换成交价分开。</p></section>
 <section className="model-section" id="cny-products"><h2>04 Product Mapping · 产品身份优先</h2><p>所有候选均未被批准为完整实盘组合。上市前只允许展示 INDEX BACKFILL，不显示 INVESTABLE RETURN；当前费率不从2011贯穿历史。511010的5年期限不等价H11006，513500/513100不替代ACWI。</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>产品 / 代码</th><th>成立 / 上市</th><th>跟踪目标与差异</th><th>已披露管理 / 托管</th><th>实施状态</th></tr></thead><tbody>{r.products.map((x:Row)=><tr key={x.code}><th>{x.name}<p>{x.code} · {x.market} · {x.currency}</p></th><td>{x.inception||'无批准产品'}<p>{x.listed||'未核实'}</p><small>{x.listing_verified?'A · 上市证据已核实':'待正式上市文件'}</small></td><td>{x.index}<p>{x.mapping_gap}</p></td><td>{pct(x.management_fee)} / {pct(x.custody_fee)}<p>披露段，不代表现时账户费率或历史有效段</p></td><td><Badge appearance="tint" color="warning">NOT VALIDATED</Badge><details><summary>机制、准入、税务与来源</summary><p>{x.mechanism}</p><p>{x.tax}</p><p>交易费、实时买卖价差、额度、折溢价、连续历史均未完整验证。跟踪误差实现值为空；{x.tracking_error_target||'无已核实跟踪目标'}。</p><p>{x.sources.join(' / ')}</p></details></td></tr>)}</tbody></table></div></section>
 {evidence&&<section className="model-section" id="cny-evidence"><h2>第二轮官方补证 · 产品净值与税主体</h2><p>7份成功原件、2次失败回执；306个既有数值CSV保持原SHA。新增披露只补产品证据，正式人民币税后合格组合仍为0。</p><Notice title="基金净值披露：独立Level 2诊断">513500跟踪标普500 Net TR，人民币比较基准含估值汇率调整。它是产品对照，不替代ACWI。费用、底层税、复制、现金与汇率口径共同影响净值差，不能单独归因为手续费。</Notice><div className="guard-grid"><div><span className="meta">2014–2021披露净值连乘年化</span><p>{pct(diagnostic.fund_cagr)}</p></div><div><span className="meta">同期披露人民币基准年化</span><p>{pct(diagnostic.benchmark_cagr)}</p></div><div><span className="meta">几何年化差 · {diagnostic.negative_years}/{diagnostic.years}年落后</span><p>{pp(diagnostic.geometric_drag)}</p></div></div><p>仅按8个完整年度的四舍五入值复算。2014年初含ETF上市前日期；不是全年可买收益。MDD、Sharpe、Sortino、二级成交和个人税后CAGR均未验证。</p><h3>带日期费率：事件与快照分别记录</h3><div className="table-scroll" tabIndex={0}><table><thead><tr><th>产品</th><th>证据类型</th><th>生效/披露日</th><th>管理/托管年费率</th><th>历史与当前资格</th></tr></thead><tbody>{evidence.fee_disclosures.map((x:Row)=><tr key={x.id}><th>{x.code}</th><td>{x.kind==='CHANGE_EVENT'?'降费事件':'披露快照'}</td><td>{x.effective||x.as_of}<p>文件：{x.published_at}</p></td><td>{pct(x.management_fee)} / {pct(x.custody_fee)}</td><td>连续历史、2026现行均未验证</td></tr>)}</tbody></table></div><p>510300自2024-11-22管理费0.50%→0.15%、托管0.10%→0.05%。513500披露指数许可费及最低费条款；2024综合运作费率0.91%为测算，不能在0.60%+0.25%之外再加，也不从真实NAV重复扣费。</p><details><summary>全部11段披露 · 包含部分期和累计期</summary><div className="table-scroll" tabIndex={0}><table><thead><tr><th>区间</th><th>基金净值增长</th><th>人民币基准增长</th><th>披露差值</th><th>日期准入边界</th></tr></thead><tbody>{evidence.product_periods.map((x:Row)=><tr key={`${x.start}-${x.end}`}><th>{x.start} → {x.end}</th><td>{pct(x.fund_return)}</td><td>{pct(x.benchmark_return)}</td><td>{pp(x.reported_gap)}</td><td>{x.date_access_label.includes('PRE-LISTING')?'含上市前日期 · 基金披露':'基金披露 · 非市场成交'}</td></tr>)}</tbody></table></div><p>原PDF第68–69页六列均保存，标准差保持原披露口径，不推断为可比年化风险。2026抓取历史文件，非已验证历史可知信息。</p></details><h3>税文件适用范围与国债变体</h3><p>财税字〔1998〕55号限定新批准封闭式证券投资基金；成文1998-08-06、追溯1998-03-01生效，首个可知发布时间未知。不能扩展为全部ETF/QDII的免税批准。</p><p>中证事实表列H01006净价、N11006利息再投资；H11006/N11006现金利息公式与历史对账仍缺，保留原强基准序列。510300年报URL日期与正文送出日冲突独立登记。</p><div className="module-links">{['V3.2_EVIDENCE_ROUND2.md','product-disclosed-periods.csv','fee-disclosures.csv','evidence-round2.json'].map(name=><a key={name} href={`./crisis-v32-cny/${name}`} download>{name}</a>)}</div></section>}
 <section className="model-section" id="cny-qdii"><h2>05 QDII Reality · NAV不等于成交价</h2><p>Premium = P_market / 同步IOPV − 1。参考净值与市场价不同时间不可直接算可套利溢价。发行人额度、剩余额度、申购开放、二级深度分别记录；海外休市、境内开市、分红与公布延迟也须处理。</p><div className="table-scroll"><table><thead><tr><th>买入溢价压力</th><th>退出溢价</th><th>V3全球30%损失</th><th>强基准全球60%损失</th><th>警示</th></tr></thead><tbody>{r.premium_stress.map((x:Row)=><tr key={x.premium}><th>{pct(x.premium)}</th><td>0%</td><td>{money(x.world_v3_loss)}</td><td>{money(x.world_strong_loss)}</td><td>{x.flag}</td></tr>)}</tbody></table></div><p>仅一次初始购买、底层NAV不变、溢价归零的机制压力，不是当日报价。1% / 3% / 5% / 10%逐级警示，不假设可以一直按NAV买入。</p></section>
 <section className="model-section" id="cny-backtest"><h2>06 After-Tax Backtest · 四层收益口径</h2><div className="guard-grid">{[['L1 毛资产','指数/理论资产；ACWI与GLD是基金代理，已含产品损耗'],['L2 产品','真实NAV含管理、托管及跟踪差，不重复扣'],['L3 投资者税前','佣金、申赎、点差、溢价及合法路径换汇'],['L4 人民币税后','(税后终值/人民币初始资本)−1；应用证据不足保持空']].map(([a,b])=><div key={a}><span className="meta">{a}</span><p>{b}</p></div>)}</div><h3>正式CNY税后比较：尚不可计算</h3><div className="table-scroll"><table><thead><tr><th>组合</th><th>真实税后CAGR</th><th>真实税后终值</th><th>状态</th></tr></thead><tbody>{r.formal_results.map((x:Row)=><tr key={x.id}><th>{x.label}</th><td>未验证</td><td>未验证</td><td>BLOCKED</td></tr>)}</tbody></table></div><h3>可复算的代理摩擦压力 · 96组全部公开</h3><div className="cny-controls"><label>场景 <Select value={scenario} onChange={(_,d)=>setScenario(d.value)}>{r.registered.scenarios.map((x:Row)=><option value={x.id} key={x.id}>{x.id} · {x.name}</option>)}</Select></label><label>再平衡 <Select value={mode} onChange={(_,d)=>setMode(d.value)}>{Object.entries(modes).map(([key,text])=><option value={key} key={key}>{text}</option>)}</Select></label></div><Notice title="D级条件压力；不是真实税后回测">单边5/15/50bp、最低0/5元、额外0/25/100bp仅估算。D额外20%已实现正利得税与50bp直接换汇是假设另一路径，不能套到默认境内QDII账户；正式税后字段始终为空。压力额外基金损耗是代理复制差，不冒充已知真实产品费用。</Notice><div className="table-scroll" tabIndex={0}><table><thead><tr><th>组合</th><th>代理压力CAGR / MDD</th><th>清算压力CAGR</th><th>周波动 / Sortino</th><th>周转 / 交易次数</th><th>交易费 / 假设税 / FX摩擦</th><th>水下 / 最差1Y / 3Y</th></tr></thead><tbody>{[...rows].sort((a:Row,b:Row)=>(a.id==='global60'?-1:b.id==='global60'?1:0)).map((x:Row)=><tr key={x.id}><th>{x.label}</th><td>{pct(x.proxy_cagr)} / {pct(x.proxy_mdd)}</td><td>{pct(x.proxy_liquidated_twr_cagr)}</td><td>{pct(x.annualised_volatility)} / {x.sortino_mar0==null?'未定义':num(x.sortino_mar0,2)}</td><td>{pct(x.turnover_annual)} / {x.trade_count}</td><td>{money(x.cumulative_transaction_cost)} / {money(x.cumulative_synthetic_tax)} / {money(x.fx_friction)}</td><td>{x.max_drawdown_duration_days}天<p>{pct(x.worst_1y)} / {pct(x.worst_3y)}</p></td></tr>)}</tbody></table></div><p>本轮08:00代理诊断先滞后一条本地日期，再在后续观测标记交易；没有恢复历史真实发布时间或08:00成交价。不能把新诊断数字替换原V3曲线。Real CAGR、Sharpe、实际跟踪误差缺CPI/RF/产品数据，留空。</p>
 <Chart title={`年度再平衡 · 场景${scenario}代理净值`} question="在相同预登记摩擦下，强基准与V3如何变化？其他再平衡规则见表格与每日CSV。" fallback={`代理年度结果：全球60/40 CAGR ${pct(annualStrong.proxy_cagr)}，V3 ${pct(annualV3.proxy_cagr)}。非实盘或真实税后结果。`} provenance="冻结代理数据 · 前一本地日期诊断 · D级摩擦假设 · 每日完整CSV可下载" option={{tooltip:{trigger:'axis'},legend:{data:curves.map((x:Row)=>x.id)},xAxis:{type:'time'},yAxis:{type:'value',scale:true},series:curves.map((x:Row)=>({type:'line',name:x.id,data:x.data.map((p:Row)=>[p.date,p.nav]),showSymbol:false}))}}/>
 <Chart title={`年度再平衡 · 场景${scenario}代理回撤`} question="日度回撤先由完整曲线计算，再抽样展示并保留最大回撤时点。" fallback={`完整日度最大回撤：强基准 ${pct(annualStrong.proxy_mdd)}，V3 ${pct(annualV3.proxy_mdd)}。恢复期与水下时间在CSV中。`} provenance="完整日CSV计算 · 显示十交易日抽样及最深回撤点 · 不是实际成交回撤" option={{tooltip:{trigger:'axis'},legend:{data:curves.map((x:Row)=>x.id)},xAxis:{type:'time'},yAxis:{type:'value',axisLabel:{formatter:'{value}%'}},series:curves.map((x:Row)=>({type:'line',name:x.id,data:x.data.map((p:Row)=>[p.date,-p.drawdown*100]),showSymbol:false}))}}/>
 <p>曲线按十观测日抽样并保留最深回撤点；每组对应时间轴按时间坐标，完整日值见复核包。</p>
 <h3>现金流优先：每月新增500元的独立实验</h3><p>新增资金发行组合单位，使用TWR剔除存款效应；总财富与净利润另列，不用“终值/最初10万元”假装收益。含分红调整代理不重复加现金股息，真实分红事件仍待齐备。</p><div className="table-scroll"><table><thead><tr><th>组合</th><th>总投入</th><th>清算压力财富</th><th>扣除投入后利润</th><th>TWR CAGR</th><th>周转</th></tr></thead><tbody>{r.cashflow_experiments.map((x:Row)=><tr key={x.id}><th>{x.label}</th><td>{money(x.contributed_cny)}</td><td>{money(x.terminal_proxy_liquidated_cny)}</td><td>{money(x.net_profit_cny)}</td><td>{pct(x.proxy_cagr)}</td><td>{pct(x.turnover_annual)}</td></tr>)}</tbody></table></div></section>
 <section className="model-section" id="cny-complexity"><h2>07 Complexity Cost Test · 复杂性值得吗？</h2><p>不把税务、账户或维护复杂度伪装成一个精确现金价格。比较新增资产、币种、准入、税务、周转和成本，再问真实税后风险调整改善是否可重复。</p><div className="table-scroll"><table><thead><tr><th>V3相对全球60/40</th><th>代理CAGR差</th><th>MDD差</th><th>周转差</th><th>交易费差</th><th>真实税后增量价值</th></tr></thead><tbody>{r.complexity.filter((x:Row)=>x.scenario===scenario).map((x:Row)=><tr key={x.mode}><th>{modes[x.mode]}<p>多2种资产；国内产品路径仍未齐</p></th><td>{pp(x.proxy_cagr_delta)}</td><td>{pp(x.proxy_mdd_delta)}</td><td>{pp(x.turnover_delta)}</td><td>{money(x.transaction_cost_delta)}</td><td>无法验证</td></tr>)}</tbody></table></div><p>这些固定样本实验不产生“最佳规则”。即使低换手保留风险控制，也须补齐真实产品、税务及连续报价后才能判断是否值得实施。</p></section>
 <section className="model-section" id="cny-verdict"><h2>08 Implementation Verdict · 证据不足就继续阻塞</h2><Notice title="FREEZE / IMPLEMENTATION BLOCKED">没有真实税后证据支持 IMPLEMENTABLE，也没有证据支持宣布全球配置必然失败。允许境内简单股债最终胜出；继续维持原权重与强基准。</Notice><ul>{r.blockers.map((b:string)=><li key={b}>{b}</li>)}</ul><details><summary>状态严格条件</summary><dl>{Object.entries(r.status_definitions).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl></details><h3>归档与后续调用</h3><p>原资格审计仅归档：{r.archive.events}条事件、{r.archive.rawBlobs}份原始资料，SHA和链核验通过。失败记录保留；每日任务仍暂停。本轮没有新增交易或伪造OOS收益。</p><code className="freeze-hash">{r.archive.head}</code><details><summary>来源、证据等级与原始资料</summary><p>A=官方法令/监管/指数/基金正式公告；B=正式交易所/券商文件；C=二级材料；D=估算。等级表示来源身份，不能替代应用核验或完整历史。</p><ul>{r.sources.map((x:Row)=><li key={x.id}><a href={x.url} target="_blank" rel="noreferrer">{x.id} · {x.name}</a> · {x.evidence_level}<p>{x.scope}</p><small>发布：{x.published_at||'未知'}；下载：{x.downloaded_at||'未保存原字节'}；{x.capture_status||''}</small></li>)}</ul></details><div className="module-links">{['V3.2_IMPLEMENTABILITY_REPORT.md','V3.2_ASSUMPTIONS.md','V3.2_DATA_AUDIT.md','V3.2_CHANGELOG.md','TEST_REPORT.md','V3.2_EVIDENCE_ROUND2.md','data_sources.json','product-mapping.csv','tax-rules.csv','proxy-stress-summary.csv','formal-aftertax-results.csv','complexity.csv','cashflow-experiments.csv'].map(name=><a key={name} href={`./crisis-v32-cny/${name}`} download>{name}</a>)}</div>{archive&&<div><h3>完整复核包</h3><div className="module-links">{archive.parts.map((part:Row)=><a key={part.name} href={`./crisis-v32-cny/${part.name}`} download>{part.name}</a>)}{archive.parts.length>1&&<><a href="./crisis-v32-cny/review-archive.json" download>合并校验清单</a><a href="./crisis-v32-cny/reassemble_cny_review.py" download>合并脚本</a></>}</div>{archive.parts.length>1&&<p>原件纳入后复核包分为{archive.parts.length}份下载。把全部分卷、校验清单和合并脚本放在同一文件夹，用Python运行合并脚本；校验通过后生成完整ZIP。</p>}</div>}<div className="module-links"><Link to="/models/hs300/implementation-qualification">原资格审计（归档）</Link><Link to="/models/hs300/crisis-freeze">V3.1冻结</Link><Link to="/models/hs300/crisis-v3">V3完整结果</Link><Link to="/models/hs300/crisis-validation">V2反证</Link><a href="./crisis-v32-cny/archive/qualification-2026-10-08/archive-receipt.json">归档回执</a></div></section>
 </div>;
}
