import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Badge, Button, Field, Select, Spinner } from '@fluentui/react-components';
import type { EChartsOption } from 'echarts';
import Chart from '../../components/Chart';
import { PageHeading, Notice, PrintButton, num } from '../../components/common';
type Row = Record<string, any>;
const pct=(v:number)=>num(v*100,2)+'%';
const labels:Record<string,string>={crisis:'危机模型',bh:'买入持有',matched:'等回撤初始静态','annual-matched':'等回撤年度再平衡','matched-fixed':'固定权重初始静态','annual-matched-fixed':'固定权重年度再平衡','matched-window-diagnostic':'逐窗口事后等回撤'};
labels['static-matched']='同口径等回撤静态';labels['static-fixed']='固定权重初始静态';labels['annual-fixed']='固定权重年度再平衡';
const definitions:Record<string,string>={cagr:'CAGR',maxDrawdown:'最大回撤',calmar:'Calmar',volatility:'年化波动率',sortino:'Sortino',ulcer:'Ulcer Index',longestUnderwaterCalendarDays:'最长水下／自然日',longestUnderwaterDays:'最长水下／交易日',maxPeakToTroughDays:'高点至谷底／交易日',timeUnderWaterFraction:'水下时间占比',maxCompletedRecoveryDays:'已完成谷底恢复／交易日',worst1Year:'最差一年',worst3YearAnnualised:'最差三年年化',dailyES95:'日度 ES 95%',finalValue:'期末财富',avgCash:'平均现金比例',medianCash:'中位现金比例',cashAbove50Days:'现金>50%／交易日',cashAbove80Days:'现金>80%／交易日',allCashDays:'全现金／交易日',turnoverAnnual:'年化单边名义换手',transactions:'成交笔数',fees:'佣金合计',realizedProfit:'实现利润',profitPerAvgRiskValue:'实现利润／平均风险市值',profitPerTotalCapital:'实现利润／初始总资本',deltaCagr:'CAGR差值',deltaMdd:'回撤差值',activations:'启动次数',diagnosticFalseStarts:'诊断误启动',maxCycleCalendarDays:'最长周期／自然日'};
Object.assign(definitions,{activation:'启动日',firstBuy:'首笔买入',lowDate:'最低点日期',lowPrice:'最低点指数',maxAssetDrawdown:'周期资产最大回撤',leftAmount:'左侧投入／元',rightAmount:'右侧投入／元',dormantDays:'休眠／交易日',totalBought:'总买入资金／元',averageBuyCost:'实际份额成本',worstFloatingPnl:'最高浮亏／元',exitDate:'最终退出',valuationDate:'估值截至',cycleCalendarDays:'周期／自然日',cycleTradingDays:'周期／交易日',accountProfit:'账户利润／元',accountCagr:'整个周期账户年化',buyHoldReturn:'同期买入持有收益',staticReturn:'同期静态组合收益',daysBeforeFirstBuy:'首次等待／交易日',cycleCashAbove50Days:'现金>50%／交易日',cycleAllCashDays:'全现金／交易日',classification:'事后分类',censored:'周期尚未完成',id:'Crisis Cycle ID'});
const percentKeys=new Set(['cagr','maxDrawdown','volatility','ulcer','timeUnderWaterFraction','worst1Year','worst3YearAnnualised','dailyES95','avgCash','medianCash','profitPerAvgRiskValue','profitPerTotalCapital','deltaCagr','deltaMdd','min','p10','p25','median','p75','p90','max','riskAssetWeight','maxAssetDrawdown','accountCagr','buyHoldReturn','staticReturn']);
function value(v:unknown,k:string){if(v===null||v===undefined)return '—';if(typeof v!=='number')return String(v);return percentKeys.has(k)?pct(v):num(v,['calmar','sortino','turnoverAnnual'].includes(k)?3:['finalValue','fees','realizedProfit'].includes(k)?2:0)}
function Table({rows,keys=['cagr','maxDrawdown','calmar','longestUnderwaterCalendarDays','avgCash','finalValue'],idKey='id'}:{rows:Row[];keys?:string[];idKey?:string}){return <div className="table-scroll" tabIndex={0}><table><thead><tr><th>方案</th>{keys.map(k=><th key={k}>{definitions[k]??k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><th>{r.label??labels[r[idKey]]??r[idKey]}</th>{keys.map(k=><td key={k}>{value(r[k],k)}</td>)}</tr>)}</tbody></table></div>}
const fileLinks=[['REPORT.md','V2稳健性验证报告'],['full-review.zip','完整复核 ZIP'],['summary.csv','全部基准 KPI'],['benchmark-nav.csv','全部基准每日净值'],['crisis-curve.csv','危机模型每日净值'],['crisis-fills.csv','完整逐笔交易账本'],['bh-curve.csv','买入持有净值'],['matched-curve.csv','等回撤静态净值'],['annual-matched-curve.csv','等回撤再平衡净值'],['rolling-starts.csv','月度滚动起点'],['yearly-starts.csv','年度起点'],['rolling-distributions.csv','分布与分位数'],['sensitivity.csv','参数扰动结果'],['crisis-cases.csv','危机周期案例'],['exits.csv','退出规则结果'],['triggers.csv','触发指数结果'],['trigger-cases.csv','触发指数逐案'],['ablations.csv','Ablation结果'],['complexity.csv','复杂度预算'],['simplified-no-volume-config.json','移除量能的简化候选'],['realism.csv','执行费用压力'],['price-total-return.csv','价格／全收益对照'],['cash-proxy.csv','货币基金缺口诊断'],['cash-proxy-alignment.csv','货币基金逐日对齐'],['data-quality.json','逐列来源与质量审计'],['DATA_SOURCES.md','数据来源说明'],['test-report.json','测试结果'],['TEST_REPORT.md','测试报告'],['manifest.json','SHA-256文件清单'],['results.json','完整机器可读结果'],['reproduce.py','一键复现入口'],['crisis_engine.py','权威回测引擎'],['crisis_v2.py','实验脚本'],['aligned-daily.csv','冻结行情输入'],['H00300-daily.csv','官方全收益序列'],['H11025-daily.csv','官方货币基金序列'],['cross-asset-opportunity.csv','六类资产机会成本'],['cross-asset-risk-matched.csv','跨资产回撤约束'],['cross-asset-results.json','跨资产机器可读结果'],['cross-asset-alignment-audit.csv','跨市场／汇率对齐'],['cross-asset-data-quality.json','跨资产数据质量'],['cross_asset_v2.py','跨资产复现脚本'],['V3_HANDOFF.md','V3读取与审计交接']];
function Viewer({data:d}:{data:Row}){
 const [metric,setMetric]=useState('maxDrawdown');const [caseId,setCaseId]=useState(4);const distribution='cagr';
 const main=d.summary.filter((r:Row)=>['crisis','bh','matched','annual-matched'].includes(r.id));
 const equity=useMemo<EChartsOption>(()=>({tooltip:{trigger:'axis'},legend:{top:0},grid:{left:12,right:12,top:70,bottom:50,containLabel:true},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:4}],xAxis:{type:'category',data:d.curves.crisis.map((r:Row)=>r[0]),axisLabel:{hideOverlap:true,formatter:(s:string)=>s.slice(0,4)}},yAxis:{type:'value',name:'总资产／元'},series:['crisis','bh','matched','annual-matched'].map(k=>({name:labels[k],type:'line',showSymbol:false,data:d.curves[k].map((r:Row)=>r[1]),lineStyle:{width:k==='crisis'?3:2}}))}),[d]);
 const drawdown=useMemo<EChartsOption>(()=>({...equity,yAxis:{type:'value',name:'回撤／%'},series:['crisis','bh','matched','annual-matched'].map(k=>({name:labels[k],type:'line',showSymbol:false,data:d.curves[k].map((r:Row)=>-r[2]*100)}))}),[d,equity]);
 const distributionPlot=useMemo<EChartsOption>(()=>{
  const keys=['crisis','bh','matched-fixed','annual-matched-fixed'];
  const rows=keys.map(k=>d.distributions.find((r:Row)=>r.strategy===k&&r.metric===distribution));
  return {tooltip:{trigger:'item'},grid:{left:12,right:12,top:30,bottom:50,containLabel:true},xAxis:{type:'category',data:keys.map(k=>labels[k]),axisLabel:{interval:0,formatter:(s:string)=>s.replace('固定权重','固定\n')}},yAxis:{type:'value',name:definitions[distribution]+'／%'},series:[{type:'boxplot',data:rows.map((r:Row)=>[r.min,r.p25,r.median,r.p75,r.max].map(x=>x*100))},{type:'scatter',symbolSize:4,itemStyle:{opacity:.45},data:keys.flatMap((k,i)=>d.rolling.filter((r:Row)=>r.strategy===k).map((r:Row)=>[i,r[distribution]*100]))}]} as EChartsOption
 },[d,distribution]);

 const mddDistribution=useMemo<EChartsOption>(()=>{
  const keys=['crisis','bh','matched-fixed','annual-matched-fixed'];const rows=keys.map(k=>d.distributions.find((r:Row)=>r.strategy===k&&r.metric==='maxDrawdown'));
  return {...distributionPlot,yAxis:{type:'value',name:'最大回撤／%'},series:[{type:'boxplot',data:rows.map((r:Row)=>[r.min,r.p25,r.median,r.p75,r.max].map(x=>x*100))},{type:'scatter',symbolSize:4,itemStyle:{opacity:.45},data:keys.flatMap((k,i)=>d.rolling.filter((r:Row)=>r.strategy===k).map((r:Row)=>[i,r.maxDrawdown*100]))}]}
 },[d,distributionPlot]);
 const excessDistribution=useMemo<EChartsOption>(()=>{
  const groups=[['crisisMinusBuyHoldCagr','相对买入持有'],['crisisMinusFixedStaticCagr','相对固定静态'],['crisisMinusWindowMatchedCagr','逐窗口等回撤']];const records=d.rolling.filter((r:Row)=>r.strategy==='crisis');
  const series=groups.map(([k])=>{const r=d.distributions.find((r:Row)=>r.strategy==='crisis'&&r.metric===k);return [r.min,r.p25,r.median,r.p75,r.max].map(v=>v*100)});
  return {tooltip:{trigger:'item'},grid:{left:12,right:12,top:30,bottom:30,containLabel:true},xAxis:{type:'category',data:groups.map(g=>g[1]),axisLabel:{interval:0}},yAxis:{type:'value',name:'CAGR差／百分点'},series:[{type:'boxplot',data:series,markLine:{silent:true,data:[{yAxis:0}]}},{type:'scatter',symbolSize:4,itemStyle:{opacity:.45},data:groups.flatMap(([k],i)=>records.map((r:Row)=>[i,r[k]*100]))}]}
 },[d]);
 const excess=useMemo<EChartsOption>(()=>{
  const rows=d.rolling.filter((r:Row)=>r.strategy==='crisis');
  return {tooltip:{trigger:'axis'},legend:{top:0},grid:{left:12,right:12,top:80,bottom:30,containLabel:true},xAxis:{type:'category',data:rows.map((r:Row)=>r.startMonth),axisLabel:{hideOverlap:true}},yAxis:{type:'value',name:'CAGR差／百分点'},series:[['crisisMinusBuyHoldCagr','相对买入持有'],['crisisMinusFixedStaticCagr','相对固定静态'],['crisisMinusWindowMatchedCagr','相对逐窗口等回撤（事后）']].map(([key,name])=>({name,type:'line',showSymbol:false,data:rows.map((r:Row)=>r[key]*100),markLine:{silent:true,data:[{yAxis:0}]}}))} as EChartsOption
 },[d]);
 const heat=useMemo<EChartsOption>(()=>{
  const p=d.sensitivity.filter((r:Row)=>r.kind==='pair'),vals=p.map((r:Row)=>r[metric]*100);
  return {tooltip:{position:'top'},grid:{left:40,right:30,top:35,bottom:85,containLabel:true},xAxis:{type:'category',name:'档距',data:['4%','5%','6%','7%']},yAxis:{type:'category',name:'γ',data:['1.2','1.6','2.0']},visualMap:{min:Math.min(...vals),max:Math.max(...vals),orient:'horizontal',left:'center',bottom:0,calculable:true,inRange:{color:['#d5e9f9','#68a5d8','#164d7e']}},series:[{type:'heatmap',data:p.map((r:Row)=>[[.04,.05,.06,.07].indexOf(r.value2),[1.2,1.6,2].indexOf(r.value),r[metric]*100]),label:{show:true,formatter:(v:Row)=>num(v.value[2],2)}}]} as EChartsOption
 },[d,metric]);
 const crossChart=useMemo<EChartsOption>(()=>({tooltip:{trigger:'axis'},legend:{top:0},grid:{left:12,right:12,top:85,bottom:40,containLabel:true},xAxis:{type:'category',data:d.cross.cnyCurves['hs300-tr'].map((r:Row)=>r[0]),axisLabel:{hideOverlap:true,formatter:(s:string)=>s.slice(0,4)}},yAxis:{type:'log',name:'10万元终值／对数轴'},series:['hs300-tr','china-treasury','gold','sp500-tr','nasdaq100-proxy','world-proxy'].map(k=>({name:d.cross.opportunity.find((r:Row)=>r.id===k).label,type:'line',showSymbol:false,data:d.cross.cnyCurves[k].map((r:Row)=>r[1])}))}),[d]);
 const selected=d.cases.find((r:Row)=>r.id===caseId)??d.cases[0];
 return <>
  <div className="tag-row"><Badge color={d.verdict==='C'?'warning':'subtle'} appearance="tint">Verdict {d.verdict}</Badge><Badge appearance="tint">价格指数研究结果</Badge><Badge color="warning" appearance="tint">PB / ERP待验证</Badge></div>
  <Notice title={`Verdict ${d.verdict} — ${d.verdictText}`}>当前证据不足以证明复杂危机状态机优于简单资产配置。初始静态股票权重{pct(d.matchedWeight)}；年度再平衡权重{pct(d.annualMatchedWeight)}。这两个权重只按历史回撤匹配，用于证伪，不能视为事前已知的配置建议。</Notice>
  <Notice title="影响结论的数据缺口">主结果是沪深300价格指数代理，不含分红。官方全收益指数已另做统一次日收盘执行对照；缺少全收益开盘值，不能与主结果混用。货币基金指数缺失140个主区间交易日，收益增强只作缺口诊断；PB、ERP和真实ETF执行仍未完成验证。3500门槛来自2026原文，历史重复使用有参数选择的回看偏差。</Notice>
  <section className="model-section" id="summary"><h2>1. Executive Summary</h2><div className="v2-summary">{main.map((r:Row)=><article className="v2-summary-card" key={r.id}><h3>{labels[r.id]}</h3><dl>{['cagr','maxDrawdown','calmar','longestUnderwaterCalendarDays','avgCash'].map(k=><div key={k}><dt>{definitions[k]}</dt><dd>{value(r[k],k)}</dd></div>)}</dl><p>期末 ¥{num(r.finalValue,2)}</p></article>)}</div><Table rows={d.summary}/><details><summary>全部风险、疼痛与资本效率指标</summary><Table rows={main} keys={Object.keys(definitions).filter(k=>k in main[0]&&!['deltaCagr','deltaMdd','activations','diagnosticFalseStarts','maxCycleCalendarDays'].includes(k))}/></details><p>未完成回撤按截至期末的水下时长计算，属于右截尾；不是已经确认的最终恢复时间。现金占用为每日现金／总资产的平均值。换手按全年交易名义金额／平均净值计算，包含初始建仓。</p></section>
  <section className="model-section"><h2>2. Equity Curve</h2><Chart title="同一笔10万元的长期净值" question="所有主要方案使用同一冻结行情、起止日期和交易成本。" option={equity} fallback={main.map((r:Row)=>`${labels[r.id]}期末${num(r.finalValue)}元`).join('；')} height={360} provenance="冻结价格指数 · 2011-10-10—2026-09-30 · 收盘信号次日开盘"/></section>
  <section className="model-section"><h2>3. Drawdown Curve</h2><Chart title="回撤深度与持续时间" question="恢复价格高点、持仓回本和账户恢复净值高点是不同概念。" option={drawdown} fallback={main.map((r:Row)=>`${labels[r.id]}最大回撤${pct(r.maxDrawdown)}，最长水下${r.longestUnderwaterCalendarDays}自然日`).join('；')} height={320}/></section>
  <section className="model-section"><h2>4. Rolling Start Test</h2><p>2011-10至2020-12共111个月度起点，均持有至2026-09-30。固定静态权重沿用完整样本的风险匹配结果；逐窗口等回撤另列，属于事后诊断。样本高度重叠、持有长度不同，不是111次独立验证。</p><Chart title={distribution==='cagr'?'图1 · 不同起点CAGR分布':'图2 · 不同起点最大回撤分布'} question="箱线展示最差、P25、中位数、P75、最好；散点保留每个起点。P10/P90另见分位数表。" option={distributionPlot} fallback="完整111个起点和各策略的全部分位数均可下载。" height={320}/><Chart title="图2 · 不同起点最大回撤分布" question="完整111个起点；箱线与散点共同展示。" option={mddDistribution} fallback="各起点回撤可从CSV完整复算。" height={320}/><Chart title="图3 · 危机模型超额收益分布" question="负数意味着落后；逐窗口风险匹配只作事后诊断。" option={excessDistribution} fallback="相对逐窗口等回撤的中位CAGR差为负。" height={300}/><Chart title="每个起点的危机模型超额收益" question="包括相对固定静态与逐窗口等回撤的CAGR差值；零线以下表示危机模型落后。" option={excess} fallback="所有超额收益及负面结果保存在rolling-starts.csv。" height={330}/><details><summary>中位数、P10、P25、P75、P90与极值</summary><Table rows={d.distributions.filter((r:Row)=>['cagr','maxDrawdown'].includes(r.metric)).map((r:Row)=>({...r,label:(labels[r.strategy]??r.strategy)+' · '+definitions[r.metric]}))} keys={['min','p10','p25','median','p75','p90','max']}/><p>此表以百分比展示，CSV保留完整精度。</p></details></section>
  <section className="model-section"><h2>5. Parameter Stability</h2><p>25组原约定单变量扰动、12组γ×档距组合，另有4组每三个月θ实验。未做收益优化。最后一档不足整档时封顶于d_max；原θ每63自然日更新，季度版本单独列出。</p><Field label="热图指标"><Select value={metric} onChange={(_,v)=>setMetric(v.value)}><option value="maxDrawdown">最大回撤／%</option><option value="cagr">CAGR／%</option><option value="ulcer">Ulcer／%</option></Select></Field><Chart title="γ与档距敏感性" question="展示整个预设网格；没有自动推荐参数或隐藏不利组合。" option={heat} fallback="全部41组参数扰动含每日账本，随完整复核包保存。" height={300}/><details><summary>查看所有单变量结果</summary><Table rows={d.sensitivity.filter((r:Row)=>r.kind!=='pair').map((r:Row)=>({...r,label:r.parameter+' = '+r.value}))}/></details></section>
  <section className="model-section"><h2>6. Crisis Episodes</h2><Field label="选择持续账户的实际周期"><Select value={String(caseId)} onChange={(_,v)=>setCaseId(Number(v.value))}>{d.cases.map((c:Row)=><option key={c.id} value={String(c.id)}>Cycle {c.id} · {c.activation} · {c.censored?'仍持有':'已退出'}</option>)}</Select></Field><div className="guard-grid">{Object.entries(selected).map(([k,v])=><div key={k}><span className="meta">{definitions[k]??k}</span><p>{v===null?'未实现／未退出':typeof v==='boolean'?(v?'是':'否'):value(v,k)}</p></div>)}</div><p>分类是事后诊断；最低点与最大跌幅只用于案例，不向状态机提供信号。2018、2020调整嵌套在2015启动周期内，不能伪造为独立启动案例。周期均比较相同起止日和周期初始本金。</p></section>
  <section className="model-section"><h2>7. Exit Rule Comparison</h2><p>A：既有前高修复且盈利；B：真实剩余成本+10%；C：沪深300站上200日均线连续20交易日；D：24/36/48个月到期次日开盘清仓；E：成本+10/+20/+30%，依次卖出初始份额的三分之一。D是明确强制清仓实验，未冒充原文“重新评估”。</p><Table rows={d.exits} keys={['cagr','maxDrawdown','ulcer','longestUnderwaterCalendarDays','maxCycleCalendarDays','transactions','turnoverAnnual','finalValue']}/><p>每个实验在各自持仓路径上保持同一买入规则；退出改变后续资金与再启动路径。不按历史收益排序选“最佳规则”。</p></section>
  <section className="model-section"><h2>8. Trigger Benchmark</h2><p>为避免将3500点硬移到另一个指数，A/B/C对照均停用绝对门槛；缺少沪深300成交额，三者均停用量能确认。A上证触发；B沪深300触发；C两指数均满足各自20日跌10%或年化跌速条件才启动，启动后沿用上证管理。不是将原模型A直接与删条件的B比较。</p><Table rows={d.triggers} keys={['activations','diagnosticFalseStarts','transactions','cagr','maxDrawdown','longestUnderwaterCalendarDays','finalValue']}/><details><summary>启动日期与周期长度</summary>{d.triggers.map((r:Row)=><p key={r.id}><strong>{r.id}</strong> · {r.activationDates.join('，')}<br/>周期自然日：{r.cycleLengths.join('，')}</p>)}</details><p>“误启动”仅指事后周期最大资产跌幅不足10%或未买入的诊断定义，不是可观察的真实危机标签。</p></section>
  <section className="model-section"><h2>9. Ablation Study</h2><Table rows={d.ablations} keys={['deltaCagr','deltaMdd','cagr','maxDrawdown','ulcer','transactions','finalValue']}/><p>no-PB与基准相同：PB本来就没有进入主模型，不能据此证明PB无效。no-dormant保留LEFT并移除休眠/唤醒；no-right-confirm在冷却结束后直接进入RIGHT。主模型只有完整退出，没有部分退出模块可删除；分批退出属于独立实验。</p><a href="./crisis-v2/complexity.csv" download>下载逐模块Complexity Budget</a></section>
  <section className="model-section"><h2>10. Data Quality</h2><p>所有原始数据均冻结并保留SHA-256。输入包含4067行（含426日预热），主区间3641个交易日。5行沪深300OHLC存在毫点舍入差，本轮原样保留；引擎只使用开盘、收盘，没有用异常最高/最低值。全收益指数额外返回2018-06-18非交易日，按既有真实交易日历排除。</p><h3>价格与全收益统一次日收盘对照</h3><Table rows={d.incomeComparisons.map((r:Row)=>({...r,label:r.scenario+' · '+labels[r.strategy]}))}/><p>全收益指数已包含红利再投资，不能再叠加ETF分红。次日收盘执行的两组共享相同约定，不能与主结果的次日开盘数字直接比较。它仍不是某只ETF实际成交。</p><h3>佣金、最低佣金、价差与跟踪误差压力</h3><details><summary>展开全部执行情景</summary><Table rows={d.realism.map((r:Row)=>({...r,label:r.scenario+' · '+r.strategy}))}/></details><p>最低佣金5元、单边价差10基点、年化跟踪损耗50基点均为预设假设；非特定券商或基金的真实费率。现金1.4%也是假设。</p><h3>官方货币基金序列：不完整诊断</h3><Table rows={d.cashComparisons.map((r:Row)=>({...r,label:r.strategy}))}/><p>140个缺失交易日保持最近已观察净值；下一次观察值的累计变化在已知后次日入账，不插值、不使用当天未知收益支付开盘订单。缺口可能改变日度回撤和现金收益时点，不能称为完整无风险收益验证。</p></section>
  <section className="model-section"><h2>11. Known Limitations</h2><ul><li>PB与ERP缺少可靠历史point-in-time序列，主回测固定ε=1，ERP停用。</li><li>PB选择A：保留原公式纠正示例。选择B若强行匹配PB=1.149、ε=1.21，斜率约0.31865；无法确认原作者意图，未采用。</li><li>3500绝对门槛有事后参数选择偏差；价格前缀因果测试不能消除这种偏差。</li><li>交易次数很少、滚动窗口重叠，无样本外优势证据；未完成周期和回撤都右截尾。</li><li>成交额仅来自原提供文件；跨指数对照为控制变量而停用量能。</li><li>官方全收益只有收盘，货币基金序列有缺口；未取得可覆盖全区间的真实ETF成交、分红与整数手序列。</li></ul></section>
  <section className="model-section"><h2>12. 跨资产机会成本与风险约束</h2><p>相同2011-10-10—2026-09-30，首日收盘归一化10万元。海外资产同时保留美元本币与人民币口径；人民币净值计入美元兑人民币变动。黄金用GLD、纳斯达克100用QQQ、全球股票用ACWI含分红代理；标普使用总回报指数。代理与原指数的费用和税收口径存在差异。</p><Table rows={d.cross.opportunity.filter((r:Row)=>!r.id.endsWith('-native'))} keys={['cagr','maxDrawdown','calmar','sortino','ulcer','longestUnderwaterCalendarDays','finalValue']}/><Chart title="六类资产：人民币财富机会成本" question="对数轴保留巨大财富差距；ETF代理已标注，未把美元收益当成人民币收益。" option={crossChart} fallback="完整人民币、本币及汇率对齐净值可下载。" height={380} provenance="中证官方指数、Yahoo发布行情、USD/CNY日线 · 不同市场当地收盘日历并集"/><h3>相同回撤约束下的股票／资产加现金</h3><Table rows={d.cross.riskMatched} keys={['riskAssetWeight','cagr','maxDrawdown','calmar','sortino','ulcer','finalValue','status']}/><p>匹配目标为危机模型37.86%。只能在0—100%范围调整权重；本身回撤更低的资产保持100%，属于满足风险上限，不能称为精确等回撤。权重只按风险匹配，未按收益选择。</p><h3>预设简单篮子：年度再平衡</h3><Table rows={d.cross.baskets} keys={['cagr','maxDrawdown','calmar','sortino','ulcer','longestUnderwaterCalendarDays','finalValue']}/><p>global60-bond40＝ACWI全球股票60%＋中国国债40%；sp50060-bond40＝标普总回报60%＋中国国债40%；global50-gold50＝ACWI全球股票50%＋GLD黄金50%。这三组比例预先指定，没有网格搜索最优组合。国债含久期风险，不能冒充现金或短债。</p><details><summary>本币指标及资产可获得性</summary><Table rows={d.cross.opportunity.filter((r:Row)=>r.id.endsWith('-native'))} keys={['currency','cagr','maxDrawdown','calmar','sortino','ulcer','finalValue']}/>{Object.entries(d.cross.metadata.availability).map(([k,v])=><p key={k}><strong>{k}</strong> · {String(v)}</p>)}</details><Notice title="更深的证伪：资产池可能比入场方法更重要">这些历史资产提供了更高收益或更低回撤的对照，支持V3先审查资产选择。它们没有证明下一轮危机会重复历史，也没有验证2011年境内10万元的实际跨境投资渠道、税费与汇兑成本。危机模型仍保留价格指数执行，而此表中国股权基准含红利；公平的同口径复杂状态机比较应结合前面的全收益审计。</Notice></section>
  <section className="model-section"><h2>历史调用与完整复核</h2><p>V2报告、数据、全部实验逐日账本、测试与脚本按版本保存。固定下载目录为 /crisis-v2/；文件清单逐项记录SHA-256。V1保留在 /crisis/。</p><div className="module-links">{fileLinks.map(([file,label])=><a key={file} href={'./crisis-v2/'+file} download>{label}</a>)}</div><p><a href="./crisis/REPORT.md" download>V1原报告</a> · <a href="./crisis/results.json" download>V1结果</a> · <a href="./crisis-v2/index.json" download>V2历史调用索引</a></p></section>
 </>
}
export default function HS300CrisisValidation(){const [data,setData]=useState<Row|null>(null),[error,setError]=useState(false);useEffect(()=>{Promise.all(['results.json','cross-asset-results.json'].map(file=>fetch('./crisis-v2/'+file).then(r=>{if(!r.ok)throw Error();return r.json()}))).then(([base,cross])=>setData({...base,cross})).catch(()=>setError(true))},[]);return <div className="page model-page"><div className="page-breadcrumb"><Link to="/models">模型实验室</Link> / <Link to="/models/hs300">沪深300</Link> / V2稳健性审计</div><PageHeading eyebrow="CRISIS VALIDATION V2" title="复杂状态机是否值得保留？" summary="第二轮稳健性回测、基准比较与模型简化审计 · 2011-10-10—2026-09-30" action={<PrintButton/>}/><Notice title="V3已基于本页Verdict C完成"><Link to="/models/hs300/crisis-v3">打开V3资产选择优先与固定风险预算审计。</Link> 本页继续作为只读V2历史快照保留。</Notice>{data?<Viewer data={data}/>:error?<Notice title="审计数据加载失败"><Button onClick={()=>window.location.reload()}>重新加载</Button><a href="./crisis-v2/REPORT.md">打开报告</a></Notice>:<Spinner label="加载V2审计结果"/>}</div>}
