import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Badge, Button, Spinner } from '@fluentui/react-components';
import { Notice, PageHeading, PrintButton, num } from '../../components/common';

type Row = Record<string, any>;
const pct = (v: number | null) => v == null ? '待验证' : `${num(v * 100, 2)}%`;

function FreezeViewer({ data }: { data: Row }) {
  const sources = Object.fromEntries(data.sources.map((s: Row) => [s.id, s]));
  const strong = data.historicalSummary.find((s: Row) => s.id === 'global60-bond40');
  const v3 = data.historicalSummary.find((s: Row) => s.id === 'v3-balanced');
  const downloads = [['REPORT.md', 'V3.1审计报告'], ['freeze.json', '冻结协议与SHA-256'], ['product-audit.csv', '产品与历史可得性'], ['sources.csv', '原始来源说明'], ['cost-sensitivity.csv', '费用压力结果'], ['premium-stress.csv', '溢价机制压力'], ['fx-attribution.csv', '汇率倍数分解'], ['oos-status.json', '样本外状态'], ['oos-nav.csv', '样本外观测账本'], ['events.jsonl', '追加事件记录'], ['execution-ledger.csv', '实际执行账本（空）'], ['test-report.json', '本轮测试报告'], ['full-review.zip', 'V3.1完整复核ZIP'], ['reproduce.py', '离线复核脚本']];
  return <>
    <Notice title="冻结快照保留，后续实施资格另立V3.2"><Link to="/models/hs300/implementation-qualification">查看八项硬门槛、产品映射与每日证据记录</Link>。本页2026-10-08初始快照不回写。</Notice>
    <div className="tag-row"><Badge color="warning" appearance="tint">FREEZE</Badge><Badge color="danger" appearance="tint">实盘可实施性未通过</Badge><Badge appearance="tint">权重30 / 30 / 30 / 10</Badge></div>
    <Notice title="先冻结，再观察">V2 Verdict C、V3 RESTRUCTURE保留。此阶段不寻找更好的历史权重，也不恢复复杂择时。全球60/40强基准继续放在首屏；产品映射和真实成本未通过，当前没有可宣称的实盘收益。</Notice>
    <section className="model-section"><h2>1. 强基准始终保留</h2><div className="freeze-comparison">
      {[strong, v3].map((s: Row) => <article className="v2-summary-card" key={s.id}><Badge color={s.id === 'global60-bond40' ? 'brand' : 'subtle'} appearance="tint">{s.id === 'global60-bond40' ? '强基准 · 不得删除' : '冻结研究组合'}</Badge><h3>{s.id === 'global60-bond40' ? 'ACWI全球股票60%＋中国国债40%' : '中国30%＋全球30%＋国债30%＋黄金10%'}</h3><dl><div><dt>历史理论CAGR</dt><dd>{pct(s.cagr)}</dd></div><div><dt>历史最大回撤</dt><dd>{pct(s.maxDrawdown)}</dd></div><div><dt>Calmar</dt><dd>{num(s.calmar, 3)}</dd></div><div><dt>最长水下</dt><dd>{s.longestUnderwaterCalendarDays}日</dd></div></dl><p>2011-10-10—2026-09-30 · 期末¥{num(s.finalValue, 0)}</p></article>)}
    </div><p className="freeze-counterevidence">V3仅在 <strong>{data.rolling.winsVsGlobal60} / {data.rolling.windows}</strong> 个滚动窗口跑赢强基准；CAGR差中位数 <strong>{pct(data.rolling.medianVsGlobal60)}</strong>。</p><Notice title="历史结果的解释边界">{data.historicalNote} 这里的40%不是美债或全球债券，不能泛化成所有“全球60/40”。</Notice></section>

    <section className="model-section"><h2>2. 2026-10-08冻结登记</h2><div className="guard-grid"><div><span className="meta">研究规则</span><p>固定30/30/30/10；年度日历再平衡；不加杠杆。</p></div><div><span className="meta">共同信息截点</span><p>北京时间08:00，只使用此前已收盘、已知并保存的观测。成交须在之后。</p></div><div><span className="meta">复查日期</span><p>{data.freeze.reviewDates.join(' · ')}</p></div></div><p>实际登记时刻：{new Date(data.freeze.registeredAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false })}（北京时间）。研究登记日与首个可用投资基准日分开保存。</p><details><summary>查看冻结指纹与更改政策</summary><code className="freeze-hash">{data.freeze.sha256}</code><p>原历史输入和档案SHA-256已锁定。新产品账户需先发布带日期的协议；不能回填拼接进旧曲线，原理论观测与强基准始终保留。</p></details></section>

    <section className="model-section"><h2>3. 样本外记录：{data.oos.nav == null ? '已登记，尚无完整基准报价' : '理论观测，实际产品仍受阻'}</h2><div className="freeze-comparison"><article className="v2-summary-card"><h3>V3理论观测</h3><dl><div><dt>净值</dt><dd>{data.oos.nav == null ? '—' : `¥${num(data.oos.nav, 0)}`}</dd></div><div><dt>CAGR</dt><dd>{pct(data.oos.cagr)}</dd></div><div><dt>最大回撤</dt><dd>{pct(data.oos.maxDrawdown)}</dd></div><div><dt>有效观测</dt><dd>{data.oos.observationCount}</dd></div></dl></article><article className="v2-summary-card"><h3>全球60/40强基准</h3><dl><div><dt>净值</dt><dd>{data.oos.strongBenchmarkNav == null ? '—' : `¥${num(data.oos.strongBenchmarkNav, 0)}`}</dd></div><div><dt>共同基准日</dt><dd>{data.oos.baselineDate || '尚未建立'}</dd></div><div><dt>实际成交</dt><dd>{data.oos.executedTrades}笔</dd></div><div><dt>产品账户</dt><dd>映射待验证</dd></div></dl></article></div><p>{data.oos.message}</p><p>未公布的当日收盘、旧历史报价与缺失产品价格保持空值。理论观测的年度重配不是成交；真实执行账本需要产品、时间、价量、费用及凭据。当前尚未接通经验证的自动行情写入渠道。</p></section>

    <section className="model-section"><h2>4. 可实施性阻塞清单</h2><div className="table-scroll" tabIndex={0}><table><thead><tr><th>状态</th><th>疑点</th><th>通过门槛</th></tr></thead><tbody>{data.blockers.map((r: Row) => <tr key={r.id}><td><Badge appearance="tint" color={r.severity === 'BLOCKED' ? 'danger' : 'warning'}>{r.severity}</Badge></td><th>{r.issue}</th><td>{r.requirement}</td></tr>)}</tbody></table></div></section>

    <section className="model-section"><h2>5. 大陆候选产品与历史可得性</h2><p>候选清单用于审计，尚未选为实际持仓。未知当日限额、申购开放和溢价留空；2011不存在的ETF不会回穿历史。</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>角色／研究资产</th><th>候选产品</th><th>成立／上市</th><th>2011存在</th><th>已核实当前管托费</th><th>主要差异与来源</th></tr></thead><tbody>{data.products.map((r: Row) => <tr key={r.code}><td>{r.role}<br/>{r.research}</td><th>{r.candidate}<br/>{r.code}</th><td>{r.inception}<br/>{r.listed || '上市日期未核'}</td><td>{r.existed2011 ? '是，非精确复制证明' : '否'}</td><td>{r.managementRate == null || r.custodyRate == null ? '待完整核验' : `${pct(r.managementRate)}＋${pct(r.custodyRate)}`}</td><td>{r.gap}<div>{r.sources.map((id: string) => <a key={id} href={sources[id].url} target="_blank" rel="noreferrer">[{id}] </a>)}</div></td></tr>)}</tbody></table></div></section>

    <section className="model-section"><h2>6. 同时向V3与强基准施加费用压力</h2><p>{data.feeNote} 不是费用最优场景选择，也没有搜索权重。</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>方案／压力</th><th>单边费用bp</th><th>最低佣金元</th><th>年度额外bp</th><th>CAGR</th><th>MDD</th><th>最长水下</th><th>期末财富</th></tr></thead><tbody>{data.costStress.map((r: Row) => <tr key={`${r.strategy}-${r.scenario}`}><th>{r.strategy === 'v3' ? 'V3' : '强基准'} · {r.scenario}</th><td>{r.tradeBp}</td><td>{r.minimumCny}</td><td>{r.annualExtraBp}</td><td>{pct(r.cagr)}</td><td>{pct(r.maxDrawdown)}</td><td>{r.longestUnderwaterCalendarDays}日</td><td>¥{num(r.finalValue, 0)}</td></tr>)}</tbody></table></div><p>账本与每日估值可下载复算。税费、真实报价冲击、渠道换汇和基金限额还没有完整验证；不能把这张表称为真实产品回测。</p><details><summary>分红、管理费与跟踪误差如何避免重复计入</summary><p>产品原始净值加实际分红事件，或含分红调整序列，选一种口径。净值内已反映的管理/托管费用及税负不再扣一遍；跟踪差不能再重复叠加。投资者佣金、最低费、价差、折溢价和换汇费用单独记录。未核实税率保持空值。</p></details></section>

    <section className="model-section"><h2>7. 汇率与溢价</h2><p>{data.currencyNote}</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>冻结代理</th><th>USD CAGR</th><th>USD/CNY CAGR</th><th>CNY CAGR</th></tr></thead><tbody>{data.fxAttribution.map((r: Row) => <tr key={r.asset}><th>{r.asset}</th><td>{pct(r.usdCagr)}</td><td>{pct(r.fxCagr)}</td><td>{pct(r.cnyCagr)}</td></tr>)}</tbody></table></div><p>增长倍数相乘：人民币增长＝美元增长×汇率增长；CAGR不能直接相加。起始全球仓位溢价5%归零、底层不变的机制压力：V3约损失¥1,429，强基准约¥2,857。不是今日实测溢价。</p><p>QDII人民币份额并不消除汇率风险；机构额度不等于基金可申购余额。跨时区IOPV不能未经核实直接充当同期公平价值。</p></section>

    <section className="model-section"><h2>8. 原始来源与可复核归档</h2><details><summary>展开{data.sources.length}条原始来源与核实范围</summary><ul>{data.sources.map((s: Row) => <li key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.title}</a>（{s.publishedDate || '未取得精确发布日期'}）：{s.verifiedClaim}</li>)}</ul></details><div className="module-links">{downloads.map(([file, label]) => <a key={file} href={`./crisis-v31/${file}`} download>{label}</a>)}</div><div className="module-links"><Link to="/models/hs300/crisis-v3">V3固定历史快照</Link><Link to="/models/hs300/crisis-validation">V2完整反证审计</Link><Link to="/models/hs300">V1纪律模型</Link><a href="./validation-index.json">全部版本机器可读索引</a></div><Notice title="仍允许最终选择更简单的方案">如果未来没有证据证明V3比全球股票60%＋中国国债40%提供额外价值，就继续简化。执行纪律不能替代可验证优势，缺失资料也不能包装成通过审计。</Notice></section>
  </>;
}

export default function HS300CrisisFreeze() {
  const [data, setData] = useState<Row | null>(null); const [error, setError] = useState(false);
  useEffect(() => { fetch('./crisis-v31/results.json').then(r => { if (!r.ok) throw Error(); return r.json(); }).then(setData).catch(() => setError(true)); }, []);
  return <div className="page model-page"><div className="page-breadcrumb"><Link to="/models">模型实验室</Link> / <Link to="/models/hs300/crisis-v3">V3</Link> / V3.1 Freeze</div><PageHeading eyebrow="CRISIS CAPITAL · V3.1 FREEZE" title="冻结规则，把研究拉回可实施性" summary="大陆产品审计 · 成本与时点 · 2026-10-08样本外预登记" action={<PrintButton/>}/>{data ? <FreezeViewer data={data}/> : error ? <Notice title="V3.1审计加载失败"><Button onClick={() => location.reload()}>重新加载</Button><a href="./crisis-v31/REPORT.md">打开报告</a></Notice> : <Spinner label="加载冻结审计与观测状态"/>}</div>;
}
