import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Badge,Button,Spinner} from '@fluentui/react-components';
import {Notice,PageHeading,PrintButton,num} from '../../components/common';
type Row=Record<string,any>;
const value=(v:number|null|undefined)=>v==null?'未披露':num(v,4);
const stamp=(s:string|null|undefined)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'未取得';
export default function HS300Implementation(){
 const [audit,setAudit]=useState<Row|null>(null),[live,setLive]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[archiveError,setArchiveError]=useState(false);
 async function refresh(){try{const r=await fetch('/api/implementation/status',{cache:'no-store'});if(!r.ok)throw Error('实时账本不可用');setLive(await r.json());setError('');}catch{setError('实时账本暂不可用，不能据此称采集成功或报价为0。');}}
 useEffect(()=>{fetch('./crisis-v32/results.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(setAudit).catch(()=>setArchiveError(true));void refresh();const t=setInterval(()=>void refresh(),60000);return()=>clearInterval(t);},[]);
 async function collect(){setBusy(true);try{const r=await fetch('/api/implementation/collect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({runKey:'v32-manual-'+new Date().toISOString().replace(/[^a-z0-9:-]/gi,'').toLowerCase()})});if(!r.ok)throw Error();await refresh();}catch{setError('采集或保存未完成。未知报价保持空值，请查看实时记录。');}finally{setBusy(false);}}
 if(!audit)return <div className="page model-page">{archiveError?<Notice title="资格审计加载失败"><a href="./crisis-v32/REPORT.md">打开报告</a></Notice>:<Spinner label="加载实施资格审计"/>}</div>;
 const strong=audit.historicalSummary.find((r:Row)=>r.id==='global60-bond40'),v3=audit.historicalSummary.find((r:Row)=>r.id==='v3-balanced');
 const fields=live?.latest||[];const prices=fields.filter((r:Row)=>r.nav!=null||r.close!=null).length;
 return <div className="page model-page"><div className="page-breadcrumb"><Link to="/models">模型实验室</Link> / <Link to="/models/hs300/crisis-freeze">V3.1冻结快照</Link> / V3.2</div>
  <PageHeading eyebrow="IMPLEMENTATION QUALIFICATION · V3.2" title="原实施资格审计（归档）：八项AND协议保留" summary="规则继续冻结 · 真实产品映射 · 每日证据记录" action={<PrintButton/>}/>
  <p><Link to="/models/hs300/cny-implementability">继续查看 V3.2 人民币税后研究</Link> · 本页原资格协议与历史证据保留。</p><div className="tag-row"><Badge color="danger" appearance="tint">BLOCKED</Badge><Badge appearance="tint">资格 {audit.passedGates} / 8</Badge><Badge appearance="tint">不调权重</Badge></div>
  <Notice title="复杂度本身是一种负债">{audit.philosophy} 每一条新规则都要说明为何不能直接使用全球股票60%＋中国国债40%。当前没有批准的完整大陆产品路径，也没有完整的样本外全收益报价集。</Notice>
  <section className="model-section"><h2>强基准仍在首屏</h2><div className="freeze-comparison">{[strong,v3].map((r:Row)=><article className="v2-summary-card" key={r.id}><Badge color={r.id==='global60-bond40'?'brand':'subtle'} appearance="tint">{r.id==='global60-bond40'?'强基准 · 不得删除':'冻结研究组合'}</Badge><h3>{r.id==='global60-bond40'?'ACWI全球股票60%＋中国国债40%':'中国30%＋全球30%＋国债30%＋黄金10%'}</h3><dl><div><dt>历史理论CAGR</dt><dd>{num(r.cagr*100,2)}%</dd></div><div><dt>历史MDD</dt><dd>{num(r.maxDrawdown*100,2)}%</dd></div><div><dt>样本外净值</dt><dd>尚无完整基准</dd></div><div><dt>实施资格</dt><dd>BLOCKED</dd></div></dl></article>)}</div><p>V3只有 {audit.rolling.winsVsGlobal60} / {audit.rolling.windows} 个滚动窗口领先。两组共享全球映射和H11006口径问题；强基准领先不等于实盘已获准。这里的国债是中国国债，不能泛化成所有全球60/40。</p><details><summary>历史结果边界</summary><p>{audit.historicalNote}</p></details></section>
  <section className="model-section"><h2>真实产品映射</h2><p>候选清单按资产身份和可复制性审计，未按历史表现排名，尚未选择实际持仓。NOT IMPLEMENTABLE表示本轮无批准路径，不宣称所有大陆产品都不存在。</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>目标</th><th>V3／强基准预算</th><th>候选工具与路线</th><th>资格与缺口</th></tr></thead><tbody>{audit.products.map((r:Row)=><tr key={r.asset}><th>{r.target}</th><td>¥{r.budgetV3.toLocaleString()}／¥{r.budgetStrong.toLocaleString()}</td><td>{r.candidate}<p>{r.toolPolicy}</p></td><td><Badge color="warning" appearance="tint">{r.mappingStatus}</Badge><p>{r.reason}</p></td></tr>)}</tbody></table></div></section>
  <section className="model-section"><h2>ImplementationScore：{audit.implementationScore} / 100</h2><p>仅描述证据完整度。必须8/8全部满足；UNKNOWN也阻塞。某一资产或某一门槛通过，不能抵消其他缺口。</p><div className="table-scroll" tabIndex={0}><table><thead><tr><th>门槛</th><th>预注册要求</th><th>本次审计</th></tr></thead><tbody>{audit.gates.map((r:Row)=><tr key={r.id}><th>{r.title}</th><td>{r.requirement}</td><td><Badge appearance="tint" color={r.status==='FAIL'?'danger':'warning'}>{r.status}</Badge><p>{r.reason}</p></td></tr>)}</tbody></table></div><details><summary>登记时刻、协议指纹与变更约束</summary><p>{stamp(audit.protocol.registeredAt)} 北京时间。工程门槛在本轮资格观察前登记，未经回测优化；改变门槛须另立带日期版本。</p><code className="freeze-hash">{audit.protocol.sha256}</code><p>原V3.1冻结指纹：</p><code className="freeze-hash">{audit.protocol.freezeHash}</code></details></section>
  <section className="model-section"><h2>每日数据：采集记录与行情资格分开</h2>{error&&<Notice title="实时状态未验证">{error}</Notice>}<div className="guard-grid"><div><span className="meta">保存的全部事件</span><p>{live?live.eventCount:'未取得'}</p></div><div><span className="meta">最新来源中有价格字段</span><p>{live?prices:'未取得'} / 12</p></div><div><span className="meta">最近保存时刻</span><p>{stamp(live?.lastRecordedAt)}</p></div></div><p>统一08:00北京时间截点。07:30为每日采集计划，启用状态与首次运行以带日期回执为准；实际保存晚于截点不能回填当天的信息集。采集失败、动态页面空值、未知FX、买卖价差及额度都保留原状态。原始NAV没有股息再投资，不能充当冻结全收益代理。</p><div className="module-links"><Button disabled={busy} onClick={()=>void collect()}>{busy?'采集与保存中':'现在采集一次'}</Button><Button onClick={()=>void refresh()}>刷新记录</Button><a href="/api/implementation/events" download="V3.2实时证据账本.jsonl">实时证据账本</a><a href="/api/implementation/status">实时状态</a><a href="./crisis-v32/runtime-verification.json">带日期的运行验证回执</a></div>
   {fields.length>0&&<div className="table-scroll" tabIndex={0}><table><thead><tr><th>来源／工具</th><th>市场时点／保存时点</th><th>NAV／Close／FX</th><th>Bid／Ask／溢价</th><th>申购／额度</th><th>状态与原始SHA</th></tr></thead><tbody>{fields.filter((r:Row)=>r.source_id!=='protocol').map((r:Row)=><tr key={r.source_id}><th>{r.instrument}<p><a href={r.source} target="_blank" rel="noreferrer">{r.source_id}</a></p></th><td>{stamp(r.timestamp)}<p>观察：{stamp(r.observed_at)}</p><p>保存：{stamp(r.recorded_at)}</p></td><td>{value(r.nav)}／{value(r.close)}／{value(r.fx)}<p>{r.price_kind}</p></td><td>{value(r.bid)}／{value(r.ask)}／{r.premium_discount==null?'未取得':`${num(r.premium_discount*100,2)}%`}</td><td>{r.subscription_status}<p>{r.quota_status}</p><p>披露额度：{r.quota==null?'未知':r.quota}</p>{r.minimum_subscription_units!=null&&<p>一级最低：{r.minimum_subscription_units.toLocaleString()}份</p>}</td><td>{r.type==='acquisition-failure'?'采集失败':r.parserStatus}<p>{r.error||''}</p>{r.sha256?<a className="freeze-hash" href={`/api/implementation/raw/${r.sha256}`} download>{r.sha256}</a>:'无响应字节，SHA保持空值'}</td></tr>)}</tbody></table></div>}
   <Notice title="尚未获得实盘资格">保存了证据，不等于连续数据已合格，更不等于实际交易。当前样本外基准日、两组净值和收益仍为空。H11006/N11006不替换，海外原始NAV与国内候选产品数据分别保存。</Notice>
  </section>
  <section className="model-section"><h2>项目原则与历史调用</h2><p>半年、一年、三年都记录相对强基准结果。若长期仍无独立价值，认真考虑V3退役。继续亏输不是调整权重或降低实施标准的理由。</p><details><summary>原始来源与核实范围</summary><ul>{audit.sources.map((s:Row)=><li key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.title}</a>：{s.claim}<p className="meta">{s.evidence}</p></li>)}</ul></details><div className="module-links">{[['REPORT.md','V3.2审计报告'],['qualification-protocol.json','资格协议'],['products.csv','产品映射CSV'],['gates.csv','八项门槛CSV'],['sources.csv','数据来源'],['TEST_REPORT.md','测试报告'],['full-review.zip','完整复核包'],['UPDATE_PROTOCOL.md','每日记录协议']].map(([file,label])=><a href={`./crisis-v32/${file}`} key={file} download>{label}</a>)}</div><div className="module-links"><Link to="/models/hs300/crisis-freeze">V3.1冻结快照</Link><Link to="/models/hs300/crisis-v3">V3</Link><Link to="/models/hs300/crisis-validation">V2完整反证</Link><a href="./validation-index.json">全部版本索引</a></div></section>
 </div>;
}
