import { Link, useLocation } from 'react-router-dom';
import { cases, caseSections, comparisonDimensions } from '../content/cases';
import { sources as S } from '../content/sources';
import { PageHeading, PrintButton, Evidence, Notice, Sources } from '../components/common';
export default function HistoryPages() {
  const id = useLocation().pathname.split('/')[2];
  if (id === 'comparison') return <div className="page"><PageHeading eyebrow="HISTORICAL COMPARISON" title="1929、2000、2008与AI周期" summary="比较结构与传导，避免把一种危机的时间表套用到另一种系统。" action={<PrintButton />} /><Evidence level="Interpretation" /><Notice title="比较矩阵的阅读边界">历史概况、研究解释和待补数据放在同一结构内，但不具有相同证据地位。当前AI列是观察框架，未连接实时财报与市场数据。</Notice><div className="table-scroll" tabIndex={0} role="region" aria-label="危机比较矩阵，可横向滚动"><table className="comparison-table"><caption className="meta" style={{ textAlign: 'left', padding: 16 }}>研究比较 · 更新2026-10-07 · 来源见下方，未补齐项明确标记</caption><thead><tr>{['维度', '1929', '2000', '2008', 'AI周期 · 框架'].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{comparisonDimensions.map(row => <tr key={row[0]}>{row.map((x, i) => <td key={i}>{x}</td>)}</tr>)}</tbody></table></div><section className="model-section"><h2>核心研究倾向</h2><Evidence level="Hypothesis" /><p>真实技术革命 + 盈利存在 + 未来增长被过度资本化，可以作为AI周期的一个研究假说。它不意味着所有企业、债权人或项目都获得正回报。</p><h3 style={{ marginTop: 20 }}>反方与证伪</h3><p>需求扩张和成本下降可能让投资被吸收。若应用端现金流、产能利用率与资本回报持续改善，应削弱过度投资判断。</p><Evidence level="Open question" /><p>需补齐跨时期盈利、杠杆、利率、财政和家庭债务的可比序列。不能用相似叙事替代结构证据。</p></section><Sources items={[S.depression, S.dotcom, S.gfc, S.ai, S.credit, S.pending]} /></div>;
  const item = cases.find(c => c.id === id);
  if (id && !item) return <div className="page empty-state"><h1>未找到案例</h1><Link to="/history">返回历史库</Link></div>;
  if (item) return <div className="page"><div className="page-breadcrumb"><Link to="/history">历史危机</Link> / {item.year}</div><PageHeading eyebrow={`${item.year} · ${item.subtitle}`} title={item.title} summary={item.summary} action={<PrintButton />} /><div className="article-layout"><article className="article"><Evidence level={item.evidence} /><Notice>历史概况依据列出的资料；当代比较属于研究解释。底部需要指定指标，资料不足处保留缺口。</Notice><dl className="article-meta"><div><dt>地区</dt><dd>{item.regions.join(' / ')}</dd></div><div><dt>更新</dt><dd>{item.updatedAt}</dd></div><div><dt>证据</dt><dd>历史来源 + 比较解释</dd></div></dl>{caseSections.map(([key, title, en]) => <section key={key} id={key}><span className="section-en">{en}</span><h2>{title}</h2><p>{item.sections[key]}</p>{['compare', 'limits', 'different'].includes(key) ? <Evidence level="Interpretation" /> : <div className="meta">依据：<a href={`#source-${item.sources[0].id}`}>[1] {item.sources[0].title}</a></div>}</section>)}<Sources items={item.sources} /><section><h2>Related</h2><div className="module-links"><Link to="/history/comparison">历史比较矩阵</Link><Link to="/research/capital-cycle">资本周期</Link><Link to="/research/methodology">研究方法</Link></div></section><section><h2>修订记录</h2><p className="meta">v0.1 · 2026-10-07 · 统一案例结构；具体数据与底部日期按来源补齐。</p></section></article><aside className="article-toc"><h3>案例目录</h3>{caseSections.map(([key, title]) => <a href={'#' + key} key={key}>{title}</a>)}<a href="#sources">来源</a></aside></div></div>;
  return <div className="page"><PageHeading eyebrow="HISTORY" title="历史危机数据库" summary="历史提供机制线索。比较今天，必须先说明结构差异。" action={<Link to="/history/comparison">打开比较矩阵</Link>} /><div className="module-links"><Link to="/research/institutions">长期制度史：税收、财政与国家能力</Link><Link to="/history/comparison">1929 / 2000 / 2008 / AI</Link></div><div className="case-grid">{cases.map(c => <article className="case-card" key={c.id}><div className="case-year">{c.year}</div><span className="eyebrow">{c.subtitle}</span><h3>{c.title}</h3><p>{c.summary}</p><Link to={'/history/' + c.id}>阅读案例</Link><div className="meta" style={{ marginTop: 12 }}>10个统一比较项 · 更新{c.updatedAt}</div></article>)}</div></div>;
}
