import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Button, Dialog, DialogSurface, DialogBody, DialogTitle, DialogContent, DialogActions, Field, Select } from '@fluentui/react-components';
import { Filter24Regular, Dismiss24Regular } from '@fluentui/react-icons';
import { research, researchById } from '../content/research';
import type { ResearchEntry } from '../content/schema';
import { PageHeading, Evidence, Sources, PrintButton, Notice, labels } from '../components/common';
export function Chain({ items }: { items: string[] }) { return <div className="chain" aria-label="传导链条">{items.map((item, i) => <span key={i} style={{ display: 'contents' }}><span>{item}</span>{i !== items.length - 1 && <b aria-hidden="true">→</b>}</span>)}</div>; }
export function ResearchList({ items = research }: { items?: ResearchEntry[] }) { return <div className="research-list">{items.map(r => <article className="research-item" key={r.id}><Evidence level={r.evidenceLevel} /><h3><Link to={'/research/' + r.id}>{r.title}</Link></h3><p>{r.summary}</p><div className="tag-row">{r.topics.map(t => <span key={t}>{t}</span>)}</div><div className="meta">{r.status} · {r.regions.join(' / ')} · 更新 {r.updatedAt}</div></article>)}</div>; }
export function ResearchArticle({ id }: { id: string }) {
  const r = researchById(id); if (!r) return <div className="page empty-state"><h1>没有找到这篇研究</h1><Link to="/research">返回研究库</Link></div>;
  return <div className="page"><div className="page-breadcrumb"><Link to="/research">研究库</Link> / {r.title}</div><PageHeading eyebrow={r.subtitle} title={r.title} summary={r.summary} action={<PrintButton />} /><div className="article-layout"><article className="article"><Evidence level={r.evidenceLevel} /><dl className="article-meta"><div><dt>状态 / 更新</dt><dd>{r.status} · {r.updatedAt}</dd></div><div><dt>地区 / 时间</dt><dd>{r.regions.join(' / ')}<br />{r.period}</dd></div><div><dt>置信说明</dt><dd>{r.confidence}</dd></div><div><dt>Topics</dt><dd>{r.topics.join(' / ')}</dd></div><div><dt>Created</dt><dd>{r.createdAt}</dd></div><div><dt>Evidence</dt><dd>{r.evidenceLevel}</dd></div></dl>{r.thesis.length > 0 && <section id="theses"><h2>研究命题与反方</h2>{r.thesis.map((t, i) => <div key={i} className="thesis-block"><Evidence level={t.level} /><h3>{t.statement}</h3><div className="thesis-grid"><div><h4>支持证据 / Supporting evidence</h4><ul>{t.supporting.map(s => <li key={s}>{s}</li>)}</ul><h4>反方 / Counterargument</h4><ul>{t.counter.map(s => <li key={s}>{s}</li>)}</ul></div><div><h4>替代解释 / Alternative explanation</h4><ul>{t.alternatives.map(s => <li key={s}>{s}</li>)}</ul><h4>证伪条件 / Falsifiers</h4><ul>{t.falsifiers.map(s => <li key={s}>{s}</li>)}</ul></div></div><h4>持续观察 / What to watch</h4><div className="tag-row">{t.watch.map(s => <span key={s}>{s}</span>)}</div></div>)}</section>}{r.mechanisms.length > 0 && <section id="mechanisms"><h2>机制路径</h2>{r.mechanisms.map((m, i) => <Chain items={m} key={i} />)}<p className="meta">关系来自研究框架；传导强度、方向与时滞须由证据检验。</p></section>}{r.sections.map(s => <section key={s.id} id={s.id}><h2>{s.title}</h2>{s.level && <Evidence level={s.level} />}{s.text.map((p, i) => <p key={i}>{p}</p>)}{s.points && <ul>{s.points.map(p => <li key={p}>{p}</li>)}</ul>}{s.sourceIds && <div className="meta">依据：{s.sourceIds.map((sid, i) => { const source = r.sources.find(x => x.id === sid); return <span key={sid}><a href={`#source-${source?.id || 'pending'}`}>[{i + 1}] {source?.title || 'Source pending'}</a>{i < s.sourceIds!.length - 1 ? ' · ' : ''}</span>; })}</div>}</section>)}<Sources items={r.sources} /><section id="related"><h2>相关研究</h2><div className="module-links">{r.related.map(id => <Link key={id} to={id === 'historical-comparison' ? '/history/comparison' : '/research/' + id}>{researchById(id)?.title || '历史比较矩阵'}</Link>)}</div></section><section id="revisions"><h2>修订记录</h2><ul className="revision-list">{r.revisions.map(v => <li key={v.version}>{v.date} · v{v.version} · {v.change}</li>)}</ul></section></article><aside className="article-toc"><h3>本页目录</h3>{r.thesis.length > 0 && <a href="#theses">研究命题与反方</a>}{r.mechanisms.length > 0 && <a href="#mechanisms">机制路径</a>}{r.sections.map(s => <a href={'#' + s.id} key={s.id}>{s.title}</a>)}<a href="#sources">来源</a><a href="#related">相关研究</a><a href="#revisions">修订记录</a><p className="meta">研究框架 · 非实时判断<br />模型与现实保持区分</p></aside></div></div>;
}
export default function ResearchPages() {
  const location = useLocation(); const id = location.pathname.split('/')[2];
  const [open, setOpen] = useState(false); const [filters, setFilters] = useState<Record<string, string>>({ topic: '', region: '', period: '', evidence: '', status: '' });
  if (id) return <ResearchArticle id={id} />;
  const topics = [...new Set(research.flatMap(r => r.topics))]; const regions = [...new Set(research.flatMap(r => r.regions))]; const periods = [...new Set(research.map(r => r.period))];
  const filtered = research.filter(r => (!filters.topic || r.topics.includes(filters.topic)) && (!filters.region || r.regions.includes(filters.region)) && (!filters.period || r.period === filters.period) && (!filters.evidence || r.evidenceLevel === filters.evidence) && (!filters.status || r.status === filters.status));
  return <div className="page"><PageHeading eyebrow="RESEARCH LIBRARY" title="研究库" summary="围绕机制组织材料，保留来源、解释与判断之间的距离。" /><Notice>这些条目来自你提供的研究纲要。原有讨论与实测数据尚未导入，条目状态均保持为Research。</Notice><div className="toolbar"><p>{filtered.length} / {research.length}篇研究 · {Object.values(filters).filter(Boolean).length}项筛选</p><Button icon={<Filter24Regular />} onClick={() => setOpen(true)}>筛选</Button></div>{Object.values(filters).some(Boolean) && <div className="filter-summary">{Object.entries(filters).filter(([, v]) => v).map(([k, v]) => <Button size="small" key={k} icon={<Dismiss24Regular />} onClick={() => setFilters(f => ({ ...f, [k]: '' }))}>{v}</Button>)}</div>}{filtered.length ? <ResearchList items={filtered} /> : <div className="empty-state"><h2>没有符合条件的研究</h2><p>放宽筛选条件，或清除筛选。</p><Button onClick={() => setFilters({ topic: '', region: '', period: '', evidence: '', status: '' })}>清除筛选</Button></div>}<Dialog open={open} onOpenChange={(_, d) => setOpen(d.open)}><DialogSurface><DialogBody><DialogTitle>筛选研究</DialogTitle><DialogContent><div className="filter-grid">{[{ key: 'topic', label: '主题', values: topics }, { key: 'region', label: '地区', values: regions }, { key: 'period', label: '时期', values: periods }, { key: 'evidence', label: '证据等级', values: Object.keys(labels) }, { key: 'status', label: '状态', values: ['Research', 'Draft', 'Reviewed'] }].map(f => <Field label={f.label} key={f.key}><Select value={filters[f.key]} onChange={(_, d) => setFilters(old => ({ ...old, [f.key]: d.value }))}><option value="">全部</option>{f.values.map(v => <option key={v}>{v}</option>)}</Select></Field>)}</div></DialogContent><DialogActions><Button onClick={() => setFilters({ topic: '', region: '', period: '', evidence: '', status: '' })}>重置</Button><Button appearance="primary" onClick={() => setOpen(false)}>显示结果</Button></DialogActions></DialogBody></DialogSurface></Dialog></div>;
}
