import type { ResearchEntry, Section, Thesis } from './schema';
import { sources as S } from './sources';
const section = (id: string, title: string, text: string, points: string[] = [], level: Section['level'] = 'Interpretation', sourceIds: string[] = ['brief']): Section => ({ id, title, text: [text], points, level, sourceIds });
const thesis = (statement: string, counter: string, falsifier: string, watch: string[], supporting: string[] = ['研究纲要提出的机制；观测数据与因果识别仍待补齐。']): Thesis => ({ statement, level: 'Hypothesis', supporting, counter: [counter], alternatives: ['共同受到利率、需求结构或政策变化影响，不能仅凭同步变化识别因果。'], falsifiers: [falsifier], watch });
function entry(x: Pick<ResearchEntry, 'id' | 'title' | 'subtitle' | 'summary' | 'topics' | 'regions' | 'sections'> & Partial<ResearchEntry>): ResearchEntry {
  return { slug: x.id, status: 'Research', updatedAt: '2026-10-07', createdAt: '2026-10-07', period: '结构研究 / 未连接实时数据', evidenceLevel: 'Interpretation', confidence: '机制讨论；未做统计识别', thesis: [], mechanisms: [], counterArguments: [], falsifiers: [], sources: [S.brief, S.pending], related: [], revisions: [{ version: '0.1', date: '2026-10-07', change: '将用户研究纲要结构化；原讨论与数据待导入。' }], ...x };
}
export const research: ResearchEntry[] = [
  entry({ id: 'capital-cycle', title: '资本积累如何形成危机反馈', subtitle: 'Capital accumulation & crisis mechanisms', summary: '从利润预期、资本开支与信用扩张出发，研究金融约束如何返回实体经济。', topics: ['资本周期', '信用', '危机机制'], regions: ['全球'],
    mechanisms: [['资本积累', '投资扩张', '信贷扩张', '资产价格与预期上升', '资本开支扩大', '边际回报下降', '盈利与估值 / 债务脱节', '融资收紧', '投资与就业下降', '消费与利润下降', '重新定价', '政策介入', '去杠杆或再通胀']],
    related: ['ai-capital', 'us-financial', 'china-property', 'methodology'],
    thesis: [thesis('盈利兑现弱于资本化预期时，信用与资产价格可能放大投资周期。', '融资结构稳健、技术进步和新需求可能支持投资，而利润率变化并非必然引发危机。', '盈利与现金流稳定兑现，且债务期限与偿付能力保持匹配。', ['投资回报与资本成本', '经营现金流', '期限错配', '家庭实际收入'])],
    sections: [section('circuit', 'M–C–M′：资本运动与再生产', '货币进入生产与交换，再以增值为目标返回货币形态。这是解释框架，不是对每家企业行为的单一描述。扩大再生产依赖需求、利润与融资共同支持。', ['产能扩张与有效需求不能相互替代', '资本过剩可能表现为回报不足，而非所有实物都过量', '分配与消费结构影响最终需求']), section('credit', '信用为何具有反身性', '资产价格上涨提高抵押能力与风险偏好，融资扩大又可能推高资产价格。反向过程中，抵押品折价、被迫出售和信用收缩可能相互强化。', ['数量约束和价格约束可能同时变化', '金融杠杆与经营杠杆分开观察', '流动性不足与资不抵债分开判断']), section('branches', '旁路、时滞与政策', '利润压力可能经由就业传导，也可能被财政支持、出口需求或债务重组缓冲。库存、工资和债务重定价存在不同的时滞。', ['外需、汇率与商品价格构成国际旁路', '救助改变损失分配与未来行为', '周期无固定年限，阶段可以跳跃或逆转']), section('observe', '需要怎样的证据', '同时核对投资、利润、信用与家庭收入；在行业和地区层面识别因果路径。单个指标阈值不足以宣布危机。', ['时间先后与合同结构', '反向因果与共同冲击', '政策介入前后的变化'], 'Open question')]
  }),
  entry({ id: 'ai-capital', title: '真实技术革命与资本回报的分离', subtitle: 'AI Capital Cycle', summary: 'AI能力进步可以真实存在，资本开支、债务与收益预期仍需逐环核对。', topics: ['AI', '资本周期', '私募信贷'], regions: ['美国', '全球'], sources: [S.brief, S.ai, S.credit, S.pending], related: ['ai-labour', 'us-financial', 'historical-comparison'],
    mechanisms: [['AI需求预期', 'GPU / 数据中心CapEx', '融资需求', '债务 / SPV / 私募信贷', '现金流兑现', '边际ROIC', '融资条件', '投资与就业']],
    thesis: [thesis('真实生产率革命与未来增长被过度资本化可以同时发生。', '需求增长、价格下降和新应用可能让投入快速被吸收。', '利用率、自由现金流与资本回报持续改善，并覆盖融资成本与折旧。', ['付费需求', '数据中心利用率', 'CapEx / 收入', '债务服务', '应用端利润'], ['BIS 2026年3月讨论AI基础设施的表内、表外融资结构。[ai-finance]', 'BIS 2026年9月讨论数字经济与私募信贷融资联系。[digital-credit]'])],
    sections: [section('technology', '技术层：能力到生产率', '模型能力、Agent、推理成本与自动化，只有通过可靠的工作流程、付费需求与组织变革才转化为收益。', ['软件生产率与白领任务替代分开观察', '能力基准分数不等于企业利润', '应用端付费、留存与任务成本是重要观察项']), section('industry', '产业层：基础设施约束', 'GPU、半导体、数据中心、电力、网络与Cooling构成投入链条。IDC与Neocloud的成本、客户集中和资产寿命需要独立分析。', ['供应链订单不等于最终应用收入', '电力、施工与设备折旧具有不同期限', '新产能与替代设备影响残值']), section('enterprise', '企业层：不同环节的账本', 'NVIDIA等上游、Hyperscaler、模型公司、SaaS、Agent企业和运营商面对不同的利润来源与风险。上游收入不能作为下游项目可收回资本的充分证明。', ['GPU企业赚钱 ≠ 模型公司赚钱', '模型公司赚钱 ≠ 数据中心项目回本', '项目资产存在 ≠ 债权人安全获得回报']), section('finance', '金融层：现金流与合同穿透', 'BIS的AI融资研究讨论企业债与表外项目安排，包括专门载体及私募信贷参与。将融资结构与实际现金流放在一起，才能讨论风险由谁承担。', ['Project Finance与企业信用分开看', '租赁承诺、SPV保证与回购条款需穿透', 'ROIC、融资利率与折旧决定回报缓冲'], 'Interpretation', ['ai-finance', 'digital-credit']), section('falsify', '应当怎样更新判断', '如果终端需求吸收产能、现金回报持续改善，应削弱过度投资假说；如果订单、利用率与融资同时恶化，应检查链条是否扩散。', ['没有连接实时财报数据', '不对当前周期给出确定阶段或概率'], 'Open question')]
  }),
  entry({ id: 'ai-labour', title: '自动化、劳动收入与需求反馈', subtitle: 'AI crisis transmission · Labour channel', summary: '替代与创造同时存在，关注任务结构、收入分配和需求如何相互作用。', topics: ['AI', '劳动', '消费'], regions: ['全球'], evidenceLevel: 'Scenario', related: ['ai-capital', 'labour', 'worktime'],
    mechanisms: [['AI能力提高', '企业自动化', '部分白领需求下降', '收入与就业增长减弱', '消费增长减弱', '服务企业收入下降', '进一步压缩成本', '进一步采用AI']],
    thesis: [thesis('若新岗位与购买力改善落后于替代，自动化可能经劳动收入反馈削弱需求。', '成本下降可能扩张需求；新岗位、价格下降与公共保障可能抵消替代。', '实际劳动收入与新就业持续增长，覆盖被替代任务损失。', ['任务暴露而非行业标签', '实际工资', '新增岗位', '消费结构'])],
    sections: [section('task', '以任务为单位观察', '一个岗位通常包含多种任务。自动化某一任务可能提高互补任务的价值，也可能减少整个岗位所需时间。', ['替代、增强、重新组织三种路径', '短期冲击与长期适应分开研究']), section('distribution', '生产率收益如何分配', '价格、工资、利润和税收共同影响最终需求。同样的技术进步，在不同制度下可能呈现不同的消费与就业结果。', ['劳动收入份额', '市场竞争程度', '保障与公共服务']), section('counter', '反馈不是必然闭环', '若降低成本促成新服务与新购买者，需求可能扩张。模型应允许正向与负向回路并存。', ['这是条件情景，非确定预测'], 'Scenario')]
  }),
  entry({ id: 'us-financial', title: '美国财政、美元与融资传导', subtitle: 'US Fiscal & Financial System', summary: '财政、国债抵押品、利率与私人融资相互连接，政策也在系统内部。', topics: ['财政', '美元', '信用'], regions: ['美国', '全球'], related: ['ai-capital', 'inflation-divergence', 'capital-cycle'],
    mechanisms: [['财政赤字与国债发行', '国债供需与期限溢价', '名义 / 实际利率', '企业融资', '资产估值', '信贷', '实体投资与就业']],
    thesis: [thesis('长期融资成本上升可经再融资与估值约束影响企业资本开支。', '强需求与名义收入增长可以支撑现金流；储备货币与抵押品需求影响国债融资。', '企业利息覆盖、投资回报与融资量维持稳健，利率变化未形成收缩。', ['利息支出', '债务到期结构', '期限溢价', '实际利率'])],
    sections: [section('fiscal', '财政：流量与存量分开', 'Federal deficit是年度流量；债务存量、Treasury issuance与debt servicing属于不同概念。interest expense受利率与到期再融资共同影响。', ['初级赤字与利息支出分别记录', '长期收益率不完全由政策利率决定', '财政空间依赖名义增长、融资条件与制度']), section('dollar', '美元：货币、资产与抵押品', '储备货币地位、国际资本流、Treasury collateral、全球美元流动性与Dollar Index并不等价。美元升值与融资紧张的关系需要按币种负债结构分析。', ['美元指数不代表所有美元流动性', '实际利率取决于期限和预期通胀', '跨境货币错配可放大压力']), section('intermediation', '金融机构与载体', 'Commercial banks、shadow banking、money market funds、Private Credit、CLO、SPV、corporate bonds、mortgage和repo通过不同合约传递风险。', ['CLO是贷款证券化结构；SPV是载体，二者不能互换', '回购依赖抵押品估值与折扣', '赎回频率与资产流动性错配需要识别']), section('data', '当前数据缺口', '尚未导入财政余额、利息支出、国债收益率、美元指数或信用序列，因此不判断当前融资压力。', ['观察值必须同时带Value、Date、Source、Updated'], 'Open question')]
  }),
  entry({ id: 'china-growth', title: '中国增长结构与有效需求', subtitle: 'China · Growth, industry & capacity', summary: '把投资、消费、出口和产业能力放在收入分配与全球需求约束中理解。', topics: ['中国经济', '工业', '需求'], regions: ['中国', '全球'], related: ['china-property', 'inflation-divergence', 'labour'],
    thesis: [thesis('相对产能压力既与生产能力有关，也可能与支付能力和需求分配有关。', '质量、技术与产品匹配不足也可能导致库存，不能把所有供给问题归因于分配。', '收入与有效需求改善后，产能仍长期无法转化为有用的消费和投资。', ['制造业利润与库存', '居民实际收入', '出口与贸易壁垒', '产能利用率'])],
    sections: [section('growth', '投资、消费与出口', '制造业、房地产和基建具有不同的融资结构、就业效应和回报期限。GDP支出项与行业增加值是不同口径，不能直接重复相加。', ['投资不是单一产业', '出口总额不等于净出口贡献', '收入、公共服务与预期影响消费']), section('industry', '生产能力怎样变成生活水平', '庞大的工业能力能否转化为真实生活资源，取决于技术、产品匹配、购买力、公共需求与分配安排。削减产能不是唯一可讨论的路径。', ['相对过剩与世界范围需求不足分开讨论', '产业出海、海外市场与贸易壁垒', '国内有效需求与生产率收益分配'], 'Open question'), section('research', '观察与识别', '需要行业、企业和家庭的多层证据，区分价格竞争、技术替代、外需冲击和国内需求不足。', ['不能仅凭PPI判断整体福利', '城市、地区与行业异质性需保留'])]
  }),
  entry({ id: 'china-property', title: '房地产与地方财政反馈', subtitle: 'China · Property, land finance & households', summary: '住房需求、土地收入、地方财政和就业之间存在相互作用，而非单向链条。', topics: ['中国经济', '房地产', '财政'], regions: ['中国'], related: ['china-growth', 'housing', 'demography'],
    mechanisms: [['房地产', '土地收入', '地方财政', '基建', '企业订单', '就业', '居民收入', '房地产需求']],
    thesis: [thesis('房地产调整可能经地方财政和家庭财富效应扩大实体压力。', '财政转移、债务重组、保障住房和其他产业需求可打断负向链条。', '土地收入减弱时，地方公共支出与居民收入得到稳定替代来源。', ['土地收入', '房企交付', 'LGFV债务', '居民杠杆', '房价与人口'])],
    sections: [section('balance', '三张资产负债表', '房企、居民与地方政府面对不同的债务和收入。银行暴露、LGFV融资与土地收入联系应依据合同和会计口径核对。', ['开发投资、销售与交付分开', '土地出让收入与经常税收分开', '居民收入与房价预期共同作用']), section('feedback', '需求与财政回路', '基建与订单可能影响就业，收入又影响购房能力。房价预期与人口变化可能改变回路强度，财政政策则可提供旁路。', ['不假定所有地区相同', '不把政策救助当作模型外部常数']), section('counter', '应对路径的研究问题', '地方财政收入结构能否调整？交付、保障性住房和债务重组如何分配损失？这些问题需要独立证据。', ['真实观察尚未导入'], 'Open question')]
  }),
  entry({ id: 'inflation-divergence', title: '一个生产体系，不同通胀路径', subtitle: 'One global production system, different inflation', summary: '外部需求扩张与内部资产调整可以沿不同回路改变价格和收入。', topics: ['通胀', '中国经济', '美元'], regions: ['中国', '美国', '欧洲'], related: ['us-financial', 'china-property', 'china-growth'], evidenceLevel: 'Scenario',
    mechanisms: [['美元财政 / 货币扩张', '全球需求', '商品', '中国生产与出口', '企业利润', '居民收入'], ['中国房地产调整', '财富效应下降', '消费减弱', '内需价格压力']],
    sections: [section('external', '外需、商品与收入传导', '财政需求、货币条件和供给瓶颈可能推动进口与商品需求。出口收入到家庭收入还经过企业成本、利润分配和税收。', ['不能把货币扩张直接等同通胀', '商品价格、消费价格和工资分别观察'], 'Scenario'), section('domestic', '内部资产负债表', '房地产财富效应、债务偿还与收入预期可能抑制消费；工业竞争和生产率变化也会改变价格。', ['住房通缩与CPI不是同一概念', 'PPI下降可能降低投入成本，也可能挤压利润'], 'Scenario'), section('identify', '结构差异与待检验项', '美国、欧洲和中国的需求、能源、住房与分配结构不同。同一个全球生产网络不意味着相同价格变化。', ['分品类与分行业观察', '区分供给冲击和需求冲击', '没有实时数据，不宣称当前各国通胀状态'], 'Open question')]
  }),
  entry({ id: 'housing', title: '2020年以来的全球住房分化', subtitle: 'Global Housing', summary: '比较利率、住房供给、人口与融资结构，而非只排房价高低。', topics: ['房地产', '人口', '信用'], regions: ['全球'], sources: [S.brief, S.housing, S.pending], related: ['china-property', 'demography', 'labour'],
    sections: [section('scope', '十个经济体，统一观察维度', '中国大陆、美国、加拿大、澳大利亚、日本、台湾、德国、英国、西班牙、意大利进入同一比较框架。当前未导入观测值，不能推断实际涨跌。', ['利率、土地、人口、移民、信贷', '收入、房租、房价收入比、城市集中', '投资属性、财政政策、住房供给']), section('rates', '利率传导取决于合同', '固定利率、浮动利率和再定价频率会改变同样利率冲击的家庭影响。供给约束和移民需求可能同时存在。', ['存量按揭与新购房者分开', '全国价格与城市结构分开', '名义价格与通胀调整后价格分开']), section('comparability', '数据口径与可比性', 'BIS住宅价格数据为比较提供来源入口，但选定序列与城市范围仍需核对。实际价格需要通胀调整，收入与租金应对齐期间。', ['价格指数不是每平方米成交价', '房价收入比必须说明分子分母口径'], 'Interpretation', ['housing']), section('question', '分化轨迹的开放问题', '政策支持、供给弹性、人口迁移与债务结构各自解释了多少？必须在取得数据后检验。', ['缺少2020年以来可比季度价格、租金和收入序列'], 'Open question')]
  }),
  entry({ id: 'labour', title: '单位有效劳动时间的生活资源', subtitle: 'Labour & Living Standards', summary: '工资、生活成本、工作时间与公共服务需要一起比较。', topics: ['劳动', '生活水平', '分配'], regions: ['全球'], related: ['worktime', 'demography', 'ai-labour'],
    sections: [section('measure', '收入与有效时间', '年可支配收入除以实际工作小时是一个切入点。加入住房、必要成本与通勤，可以形成更贴近个人约束的情景指标。', ['税前和税后不混用', '年假与实际工作周数', 'PPP使用当地货币 / 国际元的方向']), section('welfare', '完整福利不能压缩成一个数字', '社保、医疗、教育、就业稳定性、通勤与照护责任影响生活水平。相同小时资源未必对应相同安全感和公共服务。', ['家庭规模与生命周期', '现金工资与公共服务', '平均值与分位数']), section('tool', '比较器的使用边界', '使用者输入自己的情景。默认数字标注为示例，不代表任何国家真实工资、税负或购买力。', ['Housing成本单独记录', '不生成国家福利排名'], 'Scenario')]
  }),
  entry({ id: 'worktime', title: '生产率提高，收益流向哪里', subtitle: 'Productivity & Working Time', summary: '50、45和40小时周工作制是条件实验，产出、工资与就业结论取决于制度与参数。', topics: ['劳动', '生产率', '分配'], regions: ['全球'], related: ['labour', 'ai-labour', 'china-growth'], evidenceLevel: 'Open question',
    thesis: [thesis('缩短工作时间的影响取决于每小时生产率、工资安排与就业调整。', '若生产率与组织改进不足，产出或收入可能下降；若过劳减轻，生产率可能改善。', '在清晰控制工资与人员条件下，观察结果持续不符假定机制。', ['每小时产出', '年工资', '人员数量', '健康与消费'])],
    sections: [section('allocation', '五种收益去向', '工资、企业利润、国家财政、资本回报与闲暇共同构成分配问题。生产率增长不会自动转化成缩短工时。', ['市场结构与议价关系', '公共服务与税收', '再投资与资本回报']), section('experiment', '50 → 45 → 40小时', '固定人员与工作周数时，总产出等于每小时产出乘以总工时。若保持总产出，所需每小时生产率需按工时反比变化。', ['产出模型不自动决定工资', '增员、减工时和需求变化可同时发生'], 'Scenario'), section('question', '没有预设结论', '应根据行业任务、疲劳、技术采用、需求与工资政策检验，不能由算术比例替代真实实验。', ['就业、消费与社会福利需额外数据'], 'Open question')]
  }),
  entry({ id: 'demography', title: '人口结构与社会再生产', subtitle: 'Demography & Social Reproduction', summary: '人口规模、劳动生产率、自动化与保障制度共同影响再生产条件。', topics: ['人口', '劳动', '社会保障'], regions: ['全球', '中国'], related: ['housing', 'labour', 'china-property'],
    mechanisms: [['教育与住房成本', '家庭预期与婚育', '人口结构', '劳动力与抚养比', '生产率 / 自动化', '税基与保障', '家庭再生产条件']],
    sections: [section('structure', '规模与结构分开', '生育率、老龄化、劳动参与和抚养比描述不同维度。人口减少的影响取决于生产率、资本存量和分配制度。', ['不使用“人口下降=衰败”的单变量逻辑', '青年就业、技能与参与率', '人口流动与地区差异']), section('reproduction', '家庭承担了什么', '教育、房价、婚育、医疗与养老金改变家庭预算和时间。无偿照护劳动不能在模型中隐去。', ['经济成本与时间成本', '公共供给与家庭负担', '预期、稳定性与代际支持']), section('automation', '自动化与保障', '自动化可能缓解部分劳动力约束，但收益分配和税制决定其能否支持养老与公共服务。', ['产能与支付能力分开', '资本所有权与保障融资'], 'Open question')]
  }),
  entry({ id: 'institutions', title: '长期制度与财政国家', subtitle: 'Long-run Institutions', summary: '税收、军费、土地和身份制度提供长期比较问题，原历史讨论待导入。', topics: ['制度史', '财政', '国家能力'], regions: ['罗马', '中国'], period: '古代制度史 / 原始材料待补', evidenceLevel: 'Open question', related: ['us-financial', 'methodology'],
    sections: [section('roman', '罗马研究材料索引', '预留罗马共和国税制、包税人、公民制度、行省税收、帝国财政、戴克里先改革、东西罗马差异与西罗马财政瓦解等研究入口。原讨论尚未取得，当前不生成具体史实判断。', ['包税机制与国家征收能力', '税基、军费与行政网络', '公民身份、土地与产权'], 'Open question'), section('china', '中国古代税制改革', '比较税收能力、土地制度与社会组织如何相互影响。具体朝代、制度、时间和史料须在原材料提供后逐项填写。', ['不把制度名称等同真实执行', '地方征收与中央财政分开'], 'Open question'), section('limits', '长期比较的边界', '古代与现代社会在货币、技术、民主制度、市场、金融和国家能力方面存在重大差异。结构比较不是现代社会等同罗马。', ['对照机制与制度约束', '保留不可比维度'])]
  }),
  entry({ id: 'resilience', title: '危机中的行动能力', subtitle: 'Resilience', summary: '首先保住生活与收入缓冲，再研究低估资产的配置纪律。', topics: ['个人韧性', '流动性', '劳动'], regions: ['个人'], related: ['labour', 'capital-cycle', 'methodology'],
    sections: [section('liquidity', '流动性与固定成本', '现金储备应围绕必要支出、收入中断、医疗与家庭责任形成情景预算。固定成本决定失业时的现金消耗速度。', ['可用现金 / 月必要支出形成静态缓冲月数', '受限制或价格波动资产不等同现金', '不设适用于所有人的统一月数']), section('employment', '就业与技能', '识别能迁移到不同岗位和地区的能力，建立求职材料、专业联系与学习路径。评估行业集中、合同稳定性与地域移动成本。', ['Employment与Skills分别列出行动', '地理移动需要考虑住房、照护与社保']), section('debt', '债务与资产部署', '核对债务利率、到期日与收入覆盖。用于投资的预算应与生活缓冲分开，危机雷达不会触发自动买入。', ['债务期限、利率与违约后果', '目标是保留继续行动的能力', '不是预测最低点'], 'Scenario')]
  }),
  entry({ id: 'methodology', title: '研究方法：事实到判断', subtitle: 'Methodology', summary: '区分事实、数据、解释、假设、情景与判断，并让重要判断可被证伪。', topics: ['方法', '因果', '证据'], regions: ['全球'], related: ['capital-cycle', 'ai-capital', 'historical-comparison'],
    sections: [section('system', '开放、非线性与时变系统', '经济系统存在反馈、时滞、超调、外部扰动、不完全观测与内生行为。参数会改变，参与者会对模型和政策作出反应。控制工程语言可以帮助组织问题，但不能替代经验识别。', ['nonlinear system与time varying parameters', 'feedback、delay、overshoot', 'external disturbance与incomplete observation']), section('ladder', '事实 → 数据 → 解释 → 假设 → 情景 → 判断', '事实与观测并不自动给出因果解释。假设应提出可检验条件，情景明确前提，判断记录依据与不确定性。', ['数据不等于解释', '相关不等于因果', '模型不是现实', '历史比较须控制结构差异']), section('reflexivity', '反身性与政策', '市场参与者的预期改变融资和行为。政策在系统内部改变预算约束、价格和损失承担，不能永远视为外生常量。', ['市场具有反身性', '政策本身是系统变量', '判断必须允许被证伪']), section('thesis', '一条Thesis的最小要求', '每个重要命题记录支持证据、反方证据、替代解释和证伪条件。来源缺失时应留下缺口，而不是给假设贴上Fact。', ['Supporting evidence', 'Counter evidence', 'Alternative explanation', 'What would falsify this thesis']), section('evidence', '六种证据标记', 'Fact是直接数据或可核验事实；Strong evidence需多来源支持；Interpretation是解释；Hypothesis是待验证命题；Scenario是条件推演；Open question是未形成判断。', ['首版多数为研究框架和解释', '未导入数据，不使用Strong evidence描述现状', '模型输出与观测值始终分开'])]
  }),
];
export const researchById = (id: string) => research.find(x => x.id === id);
