import { useState } from 'react';
import { Button, OverlayDrawer, DrawerHeader, DrawerHeaderTitle, DrawerBody } from '@fluentui/react-components';
import { Dismiss24Regular, BrainCircuit24Regular, Building24Regular, Money24Regular, People24Regular, BuildingGovernment24Regular, Globe24Regular } from '@fluentui/react-icons';
import { Link } from 'react-router-dom';
import { Evidence } from './common';
const layers = [
  { id: 'technology', en: 'Technology', title: '技术与生产率', sub: 'AI · 自动化 · 技术扩散', icon: BrainCircuit24Regular, definition: '技术改变任务成本、生产能力与组织方式。', mechanism: '能力提升可以推动投资与生产率，也可能带来岗位替代。影响方向由需求、分配与组织采用决定。', indicators: ['任务成本', '企业采用与付费', '每小时生产率'], links: ['ai-capital', 'ai-labour'], cases: ['2000', '1973'] },
  { id: 'corporate', en: 'Corporate', title: '企业与资本', sub: '收入 · 利润 · CapEx · ROIC', icon: Building24Regular, definition: '企业投入资本并组织生产，现金回报需覆盖成本。', mechanism: '预期利润推动投资；回报不足可能影响再融资与资本开支。', indicators: ['经营现金流', '资本开支', '债务覆盖与回报'], links: ['ai-capital', 'capital-cycle'], cases: ['2000', '2008'] },
  { id: 'financial', en: 'Financial', title: '信用与金融', sub: '债务 · 利率 · 流动性', icon: Money24Regular, definition: '融资把跨期资源与风险连接起来。', mechanism: '抵押品估值、杠杆和期限错配可以相互强化，也可放大被迫出售。', indicators: ['信用利差', '期限结构', '融资折扣'], links: ['us-financial', 'capital-cycle'], cases: ['1987', '1997', '2008'] },
  { id: 'household', en: 'Household', title: '劳动与家庭', sub: '就业 · 工资 · 消费 · 按揭', icon: People24Regular, definition: '家庭同时是劳动供给者、消费者与资产持有者。', mechanism: '收入、财富与债务负担影响消费；消费变化又返回企业收入。', indicators: ['实际工资', '就业与工时', '消费与债务服务'], links: ['labour', 'china-property'], cases: ['1929', '2008', '2020'] },
  { id: 'government', en: 'Government', title: '财政与政策', sub: '税收 · 赤字 · 保障 · 干预', icon: BuildingGovernment24Regular, definition: '国家通过税收、支出、监管与央行工具改变约束。', mechanism: '政策缓冲可能改变风险承担和需求，也会反馈到融资与预期。', indicators: ['利息支出', '财政余额', '公共保障'], links: ['us-financial', 'institutions'], cases: ['1929', '2008', '2020'] },
  { id: 'global', en: 'Global', title: '全球传导', sub: '贸易 · 美元 · 商品 · 资本流', icon: Globe24Regular, definition: '跨境生产、贸易与金融构成开放系统。', mechanism: '需求、汇率和资金流可以沿供应链与资产负债表跨境传递。', indicators: ['贸易结构', '币种错配', '商品与资本流'], links: ['inflation-divergence', 'china-growth'], cases: ['1973', '1997', '2008'] },
];
export default function SystemMap({ compact = false }: { compact?: boolean }) {
  const [selected, setSelected] = useState<typeof layers[number] | null>(null);
  return <><div className={`system-map ${compact ? 'compact' : ''}`}><div className="map-context"><span className="eyebrow">开放系统 · 多向反馈</span><span className="meta">点击节点探索机制</span></div><div className="map-layers">{layers.map((l, i) => <div className="map-layer" key={l.id}><Button className="node" appearance="subtle" onClick={() => setSelected(l)}><span className={`node-icon tone-${i}`}><l.icon /></span><span><small>{l.en}</small><strong>{l.title}</strong><span className="node-sub">{l.sub}</span></span></Button>{i < layers.length - 1 && <span className="map-connector" aria-hidden="true">↓</span>}</div>)}</div><div className="feedback-strip"><span>预期 ↔ 资产价格 ↔ 融资</span><span>收入 ↔ 消费 ↔ 利润</span><span>政策 ↔ 系统行为</span></div><p className="meta">结构关系用于研究；箭头不代表已识别的因果强度，也不标示当前状态。</p></div><OverlayDrawer position="end" open={!!selected} onOpenChange={(_, d) => { if (!d.open) setSelected(null); }} className="detail-drawer"><DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" icon={<Dismiss24Regular />} aria-label="关闭节点详情" onClick={() => setSelected(null)} />}>{selected?.title}</DrawerHeaderTitle></DrawerHeader>{selected && <DrawerBody><div className="eyebrow">{selected.en}</div><Evidence level="Interpretation" /><h3>定义</h3><p>{selected.definition}</p><h3>传导机制</h3><p>{selected.mechanism}</p><h3>领先观察项</h3><ul>{selected.indicators.map(t => <li key={t}>{t}</li>)}</ul><h3>相关研究</h3>{selected.links.map(id => <Link className="detail-link" key={id} to={`/research/${id}`} onClick={() => setSelected(null)}>{({ 'ai-capital': 'AI资本周期', 'ai-labour': '自动化与劳动', 'capital-cycle': '资本积累与危机', 'us-financial': '美国财政与美元', labour: '劳动与生活水平', 'china-property': '房地产与地方财政', institutions: '长期制度史', 'inflation-divergence': '全球通胀分化', 'china-growth': '中国增长结构' } as Record<string, string>)[id]}</Link>)}<h3>历史线索</h3><div className="tag-row">{selected.cases.map(id => <Link to={`/history/${id}`} key={id} onClick={() => setSelected(null)}>{id}</Link>)}</div><p className="meta">来源：用户研究纲要 · 2026-10-07 · 历史线索不代表结构等同。</p></DrawerBody>}</OverlayDrawer></>;
}
